import SixBirdsMetaMath

#print axioms SixBirdsMetaMath.FoundationsIV.Access.HiddennessNormalForm.hiddenness_normal_form
#print axioms SixBirdsMetaMath.FoundationsIV.Access.HiddennessNormalForm.hiddenness_exposure_collapse_surplus
#print axioms SixBirdsMetaMath.FoundationsIV.Access.HiddennessNormalForm.hiddenness_normal_form_with_exposure_collapse_surplus
#print axioms SixBirdsMetaMath.FoundationsIV.Access.HiddennessNormalForm.hiddenness_normal_form_of_source_obligation
#print axioms SixBirdsMetaMath.FoundationsIV.Access.HiddennessNormalForm.hiddenness_source_obligation_satisfiable
#print axioms SixBirdsMetaMath.FoundationsIV.Access.HiddennessNormalForm.hiddenness_source_obligation_with_surplus_satisfiable
#print axioms SixBirdsMetaMath.FoundationsIV.Access.HiddennessNormalForm.HiddennessSourceObligation
#print axioms SixBirdsMetaMath.FoundationsIV.Access.HiddennessNormalForm.exposedUnitInterface
#print axioms SixBirdsMetaMath.FoundationsIV.Access.HiddennessNormalForm.hiddenBoolInterface
