import SixBirdsMetaMath.FoundationsIV.Transport.DescentRepair

/-!
F27 Conservation as Orbit Descent.

A conserved quantity is a readout that ignores every distinction generated by
the declared route family. Equivalently, it descends to the route-orbit
quotient. Complete-invariant, layer-visible, budgeted, balance-law, and
interface-mediated variants are separate statuses.
-/

namespace SixBirdsMetaMath.FoundationsIV.StatusRecordsCoherence.ConservationAsOrbitDescent

open SixBirdsMetaMath.FoundationsIV.Transport.DescentRepair

/-- A supplied orbit quotient map represents the declared orbit equivalence. -/
def OrbitQuotientCompatible {X Orbit : Type} (p : X → Orbit)
    (OrbitEquivalent : X → X → Prop) : Prop :=
  ∀ x x', p x = p x' ↔ OrbitEquivalent x x'

/-- A quantity is conserved along the declared orbit relation. -/
def ConservedAlongOrbit {X V : Type} (OrbitEquivalent : X → X → Prop)
    (quantity : X → V) : Prop :=
  ∀ x x', OrbitEquivalent x x' → quantity x = quantity x'

/-- Conservation obstruction: same route orbit, different quantity value. -/
def ConservationObstruction {X V : Type} (OrbitEquivalent : X → X → Prop)
    (quantity : X → V) : (X × X) → Prop :=
  fun pair => OrbitEquivalent pair.1 pair.2 ∧ quantity pair.1 ≠ quantity pair.2

/-- No conservation obstruction is present. -/
def ConservationObstructionEmpty {X V : Type} (OrbitEquivalent : X → X → Prop)
    (quantity : X → V) : Prop :=
  ObstructionEmpty (ConservationObstruction OrbitEquivalent quantity)

/-- The quantity descends to the supplied orbit quotient. -/
def OrbitReadoutDescends {X Orbit V : Type} (p : X → Orbit) (quantity : X → V) :
    Prop :=
  Descends p (fun x : X => x) quantity

/-- Orbit-quotient split obstruction for the supplied quotient map. -/
def OrbitReadoutSplitPair {X Orbit V : Type} (p : X → Orbit) (quantity : X → V) :
    (X × X) → Prop :=
  splitPairObstruction p (fun x : X => x) quantity

/-- No supplied-quotient orbit readout obstruction is present. -/
def OrbitReadoutSplitPairEmpty {X Orbit V : Type} (p : X → Orbit)
    (quantity : X → V) : Prop :=
  ObstructionEmpty (OrbitReadoutSplitPair p quantity)

/-- The route itself descends to a layer quotient. -/
def RouteDescendsAtQuotient {H Q : Type} (q : H → Q) (route : H → H) :
    Prop :=
  Descends q route q

/-- Route descent obstruction at a layer quotient. -/
def RouteDescentObstruction {H Q : Type} (q : H → Q) (route : H → H) :
    (H × H) → Prop :=
  splitPairObstruction q route q

/-- No route descent obstruction is present. -/
def RouteDescentObstructionEmpty {H Q : Type} (q : H → Q) (route : H → H) :
    Prop :=
  ObstructionEmpty (RouteDescentObstruction q route)

/-- A raw quantity is current-visible and conserved when it first descends to
the layer quotient and then descends to the layer route-orbit quotient. -/
def LayerVisibleAndConserved {H Q Orbit V : Type} (q : H → Q)
    (p : Q → Orbit) (rawQuantity : H → V) : Prop :=
  ∃ quantity : Q → V, quantity ∘ q = rawQuantity ∧
    Descends p (fun a : Q => a) quantity

/-- The compact layer conservation equation `raw = Cbar ∘ p ∘ q`. -/
def CompositeLayerConservation {H Q Orbit V : Type} (q : H → Q)
    (p : Q → Orbit) (rawQuantity : H → V) : Prop :=
  ∃ quantityBar : Orbit → V, (quantityBar ∘ p) ∘ q = rawQuantity

/-- A quantity separates route orbits when equal values imply same orbit. -/
def OrbitSeparating {X V : Type} (OrbitEquivalent : X → X → Prop)
    (quantity : X → V) : Prop :=
  ∀ x x', quantity x = quantity x' → OrbitEquivalent x x'

/-- Separation obstruction: different route orbits with the same quantity
value. -/
def OrbitSeparationObstruction {X V : Type} (OrbitEquivalent : X → X → Prop)
    (quantity : X → V) : (X × X) → Prop :=
  fun pair => ¬ OrbitEquivalent pair.1 pair.2 ∧ quantity pair.1 = quantity pair.2

/-- No orbit-separation obstruction is present. -/
def OrbitSeparationObstructionEmpty {X V : Type}
    (OrbitEquivalent : X → X → Prop) (quantity : X → V) : Prop :=
  ObstructionEmpty (OrbitSeparationObstruction OrbitEquivalent quantity)

/-- A complete invariant is conserved and separates route orbits. -/
def CompleteRouteInvariant {X V : Type} (OrbitEquivalent : X → X → Prop)
    (quantity : X → V) : Prop :=
  ConservedAlongOrbit OrbitEquivalent quantity ∧ OrbitSeparating OrbitEquivalent quantity

/-- A coarse conserved quantity is conserved but not complete. -/
def CoarseConservedQuantity {X V : Type} (OrbitEquivalent : X → X → Prop)
    (quantity : X → V) : Prop :=
  ConservedAlongOrbit OrbitEquivalent quantity ∧ ¬ OrbitSeparating OrbitEquivalent quantity

/-- Invariance on route generators. -/
def RouteGeneratorInvariant {X V Route : Type} (routes : Route → X → X)
    (quantity : X → V) : Prop :=
  ∀ route x, quantity (routes route x) = quantity x

/-- Generator-level conservation obstruction. -/
def RouteGeneratorObstruction {X V Route : Type} (routes : Route → X → X)
    (quantity : X → V) : Route × X → Prop :=
  fun item => quantity (routes item.1 item.2) ≠ quantity item.2

/-- No generator-level conservation obstruction is present. -/
def RouteGeneratorObstructionEmpty {X V Route : Type} (routes : Route → X → X)
    (quantity : X → V) : Prop :=
  ObstructionEmpty (RouteGeneratorObstruction routes quantity)

/-- Source status vocabulary for conservation claims. -/
inductive ConservationStatus where
  | exactConservedQuantity
  | completeRouteInvariant
  | coarseConservedQuantity
  | routeUndefinedAtQuotient
  | notConserved
  | budgetedConservation
  | balanceLaw
  | interfaceMediatedConservation
  | covariantQuantity
  | hiddenConservedQuantity
  | localConservation
  | protocolArtifact
  | conservationOverread
deriving DecidableEq

/-- Meaning assignment for F27 conservation statuses. -/
def ConservationStatusHolds (exact complete coarse routeUndefined drift budgeted
    balance interfaceMediated covariant hidden localStatus protocol overread : Prop) :
    ConservationStatus → Prop
  | ConservationStatus.exactConservedQuantity => exact
  | ConservationStatus.completeRouteInvariant => complete
  | ConservationStatus.coarseConservedQuantity => coarse
  | ConservationStatus.routeUndefinedAtQuotient => routeUndefined
  | ConservationStatus.notConserved => drift
  | ConservationStatus.budgetedConservation => budgeted
  | ConservationStatus.balanceLaw => balance
  | ConservationStatus.interfaceMediatedConservation => interfaceMediated
  | ConservationStatus.covariantQuantity => covariant
  | ConservationStatus.hiddenConservedQuantity => hidden
  | ConservationStatus.localConservation => localStatus
  | ConservationStatus.protocolArtifact => protocol
  | ConservationStatus.conservationOverread => overread

/-- Conservation is exactly absence of same-orbit/different-value obstruction. -/
theorem conserved_iff_no_conservation_obstruction {X V : Type}
    (OrbitEquivalent : X → X → Prop) (quantity : X → V) :
    ConservedAlongOrbit OrbitEquivalent quantity ↔
      ConservationObstructionEmpty OrbitEquivalent quantity := by
  constructor
  · intro hcons pair hobs
    exact hobs.2 (hcons pair.1 pair.2 hobs.1)
  · intro hempty x x' horbit
    exact Classical.byContradiction (fun hneq =>
      hempty (x, x') ⟨horbit, hneq⟩)

/-- A conserved quantity is exactly a function on the supplied route-orbit
quotient. -/
theorem conserved_iff_orbit_readout_descends {X Orbit V : Type}
    (p : X → Orbit) (OrbitEquivalent : X → X → Prop) (quantity : X → V)
    (hp : Function.Surjective p)
    (hcompat : OrbitQuotientCompatible p OrbitEquivalent) :
    ConservedAlongOrbit OrbitEquivalent quantity ↔ OrbitReadoutDescends p quantity := by
  constructor
  · intro hcons
    have hempty : OrbitReadoutSplitPairEmpty p quantity := by
      intro pair hpair
      exact hpair.2 (hcons pair.1 pair.2 ((hcompat pair.1 pair.2).1 hpair.1))
    exact (descent_repair_normal_form p (fun x : X => x) quantity hp).2 hempty
  · intro hdesc x x' horbit
    rcases hdesc with ⟨quantityBar, hcomm⟩
    have hx : quantityBar (p x) = quantity x := congrFun hcomm x
    have hx' : quantityBar (p x') = quantity x' := congrFun hcomm x'
    have hpx : p x = p x' := (hcompat x x').2 horbit
    calc
      quantity x = quantityBar (p x) := hx.symm
      _ = quantityBar (p x') := by rw [hpx]
      _ = quantity x' := hx'

/-- Descent through the supplied orbit quotient is exactly the ordinary
split-pair criterion. -/
theorem orbit_readout_descends_iff_no_split {X Orbit V : Type} (p : X → Orbit)
    (quantity : X → V) (hp : Function.Surjective p) :
    OrbitReadoutDescends p quantity ↔ OrbitReadoutSplitPairEmpty p quantity :=
  descent_repair_normal_form p (fun x : X => x) quantity hp

/-- A route is well-defined at a layer quotient exactly when its route descent
obstruction is empty. -/
theorem route_descends_iff_no_route_obstruction {H Q : Type} (q : H → Q)
    (route : H → H) (hq : Function.Surjective q) :
    RouteDescendsAtQuotient q route ↔ RouteDescentObstructionEmpty q route :=
  descent_repair_normal_form q route q hq

/-- The layer-relative two-stage definition is equivalent to the compact
equation `raw = Cbar ∘ p ∘ q`. -/
theorem layer_visible_conserved_iff_composite {H Q Orbit V : Type} (q : H → Q)
    (p : Q → Orbit) (rawQuantity : H → V) :
    LayerVisibleAndConserved q p rawQuantity ↔
      CompositeLayerConservation q p rawQuantity := by
  constructor
  · intro hlayer
    rcases hlayer with ⟨quantity, hvisible, quantityBar, hdesc⟩
    refine ⟨quantityBar, ?_⟩
    funext h
    calc
      quantityBar (p (q h)) = quantity (q h) := congrFun hdesc (q h)
      _ = rawQuantity h := congrFun hvisible h
  · intro hcomp
    rcases hcomp with ⟨quantityBar, hcomp⟩
    refine ⟨quantityBar ∘ p, hcomp, ?_⟩
    refine ⟨quantityBar, ?_⟩
    funext a
    rfl

/-- Orbit separation is exactly absence of different-orbit/same-value pairs. -/
theorem orbit_separating_iff_no_separation_obstruction {X V : Type}
    (OrbitEquivalent : X → X → Prop) (quantity : X → V) :
    OrbitSeparating OrbitEquivalent quantity ↔
      OrbitSeparationObstructionEmpty OrbitEquivalent quantity := by
  constructor
  · intro hsep pair hobs
    exact hobs.1 (hsep pair.1 pair.2 hobs.2)
  · intro hempty x x' hvalue
    exact Classical.byContradiction (fun hnotOrbit =>
      hempty (x, x') ⟨hnotOrbit, hvalue⟩)

/-- Complete invariant status is conservation plus no separation obstruction. -/
theorem complete_invariant_iff_conserved_and_no_separation {X V : Type}
    (OrbitEquivalent : X → X → Prop) (quantity : X → V) :
    CompleteRouteInvariant OrbitEquivalent quantity ↔
      ConservedAlongOrbit OrbitEquivalent quantity ∧
        OrbitSeparationObstructionEmpty OrbitEquivalent quantity := by
  constructor
  · intro hcomplete
    exact ⟨hcomplete.1,
      (orbit_separating_iff_no_separation_obstruction OrbitEquivalent quantity).1
        hcomplete.2⟩
  · intro h
    exact ⟨h.1,
      (orbit_separating_iff_no_separation_obstruction OrbitEquivalent quantity).2
        h.2⟩

/-- Generator invariance is exactly absence of generator-level drift. -/
theorem route_generator_invariant_iff_no_obstruction {X V Route : Type}
    (routes : Route → X → X) (quantity : X → V) :
    RouteGeneratorInvariant routes quantity ↔
      RouteGeneratorObstructionEmpty routes quantity := by
  constructor
  · intro hinv item hobs
    exact hobs (hinv item.1 item.2)
  · intro hempty route x
    exact Classical.byContradiction (fun hneq =>
      hempty (route, x) hneq)

/--
Conservation as Orbit Descent Normal Form. Conservation along declared route
orbits is equivalent to empty conservation obstruction and to descent through
the route-orbit quotient. Layer-visible conservation factors through the access
quotient and then the orbit quotient. Complete-invariant and generator-level
claims are separate obstruction gates.
-/
theorem conservation_as_orbit_descent {X Orbit V H Q LayerOrbit Route : Type}
    (p : X → Orbit) (OrbitEquivalent : X → X → Prop) (quantity : X → V)
    (q : H → Q) (route : H → H) (rawQuantity : H → V)
    (layerOrbit : Q → LayerOrbit) (routes : Route → X → X)
    (hp : Function.Surjective p) (hq : Function.Surjective q)
    (hcompat : OrbitQuotientCompatible p OrbitEquivalent) :
    (ConservedAlongOrbit OrbitEquivalent quantity ↔
      ConservationObstructionEmpty OrbitEquivalent quantity) ∧
      (ConservedAlongOrbit OrbitEquivalent quantity ↔ OrbitReadoutDescends p quantity) ∧
        (OrbitReadoutDescends p quantity ↔ OrbitReadoutSplitPairEmpty p quantity) ∧
          (RouteDescendsAtQuotient q route ↔ RouteDescentObstructionEmpty q route) ∧
            (LayerVisibleAndConserved q layerOrbit rawQuantity ↔
              CompositeLayerConservation q layerOrbit rawQuantity) ∧
              (CompleteRouteInvariant OrbitEquivalent quantity ↔
                ConservedAlongOrbit OrbitEquivalent quantity ∧
                  OrbitSeparationObstructionEmpty OrbitEquivalent quantity) ∧
                (RouteGeneratorInvariant routes quantity ↔
                  RouteGeneratorObstructionEmpty routes quantity) := by
  exact ⟨conserved_iff_no_conservation_obstruction OrbitEquivalent quantity,
    conserved_iff_orbit_readout_descends p OrbitEquivalent quantity hp hcompat,
    orbit_readout_descends_iff_no_split p quantity hp,
    route_descends_iff_no_route_obstruction q route hq,
    layer_visible_conserved_iff_composite q layerOrbit rawQuantity,
    complete_invariant_iff_conserved_and_no_separation OrbitEquivalent quantity,
    route_generator_invariant_iff_no_obstruction routes quantity⟩

/-- The equivalence relation generated by the declared route steps. -/
inductive RouteGeneratedOrbit {X Route : Type} (routes : Route → X → X) :
    X → X → Prop where
  | refl (x : X) : RouteGeneratedOrbit routes x x
  | step (route : Route) (x : X) :
      RouteGeneratedOrbit routes x (routes route x)
  | symm {x y : X} : RouteGeneratedOrbit routes x y →
      RouteGeneratedOrbit routes y x
  | trans {x y z : X} : RouteGeneratedOrbit routes x y →
      RouteGeneratedOrbit routes y z → RouteGeneratedOrbit routes x z

/-- Stepwise invariance is exactly descent through the quotient of the
equivalence generated by those steps. -/
theorem route_step_invariant_iff_orbit_descends
    {X Route Orbit V : Type} (routes : Route → X → X)
    (p : X → Orbit) (quantity : X → V)
    (hp : Function.Surjective p)
    (hcompat : OrbitQuotientCompatible p (RouteGeneratedOrbit routes)) :
    RouteGeneratorInvariant routes quantity ↔ OrbitReadoutDescends p quantity := by
  rw [← conserved_iff_orbit_readout_descends p (RouteGeneratedOrbit routes)
    quantity hp hcompat]
  constructor
  · intro hstep x y hroute
    induction hroute with
    | refl x => rfl
    | step route x => exact (hstep route x).symm
    | symm _ ih => exact ih.symm
    | trans _ _ ih1 ih2 => exact ih1.trans ih2
  · intro hcon route x
    exact (hcon x (routes route x) (RouteGeneratedOrbit.step route x)).symm

/-- A partial route contributes a generating pair only where it is defined. -/
inductive PartialRouteGeneratedOrbit {X Route : Type}
    (routes : Route → X → Option X) : X → X → Prop where
  | refl (x : X) : PartialRouteGeneratedOrbit routes x x
  | step (route : Route) (x y : X) (h : routes route x = some y) :
      PartialRouteGeneratedOrbit routes x y
  | symm {x y : X} : PartialRouteGeneratedOrbit routes x y →
      PartialRouteGeneratedOrbit routes y x
  | trans {x y z : X} : PartialRouteGeneratedOrbit routes x y →
      PartialRouteGeneratedOrbit routes y z →
        PartialRouteGeneratedOrbit routes x z

/-- The actual quotient by the equivalence generated by partial routes. -/
def partialRouteOrbitSetoid {X Route : Type}
    (routes : Route → X → Option X) : Setoid X where
  r := PartialRouteGeneratedOrbit routes
  iseqv := by
    constructor
    · intro x
      exact PartialRouteGeneratedOrbit.refl x
    · intro x y h
      exact PartialRouteGeneratedOrbit.symm h
    · intro x y z h h'
      exact PartialRouteGeneratedOrbit.trans h h'

/-- Canonical orbit quotient map for a declared family of partial routes. -/
def partialRouteOrbitQuotient {X Route : Type}
    (routes : Route → X → Option X) : X → Quotient (partialRouteOrbitSetoid routes) :=
  Quotient.mk (partialRouteOrbitSetoid routes)

/-- Conservation along each defined partial step. -/
def PartialRouteGeneratorInvariant {X Route V : Type}
    (routes : Route → X → Option X) (quantity : X → V) : Prop :=
  ∀ route x y, routes route x = some y → quantity y = quantity x

/-- F27 for partial routes: generator invariance is precisely constancy on
generated orbit classes and descent to their canonical quotient. -/
theorem partial_route_step_invariant_iff_orbit_descends
    {X Route V : Type} (routes : Route → X → Option X)
    (quantity : X → V) :
    (PartialRouteGeneratorInvariant routes quantity ↔
      ∀ x y, PartialRouteGeneratedOrbit routes x y →
        quantity x = quantity y) ∧
    (PartialRouteGeneratorInvariant routes quantity ↔
      OrbitReadoutDescends (partialRouteOrbitQuotient routes) quantity) := by
  have hsteps : PartialRouteGeneratorInvariant routes quantity ↔
      ∀ x y, PartialRouteGeneratedOrbit routes x y →
        quantity x = quantity y := by
    constructor
    · intro hstep x y hroute
      induction hroute with
      | refl x => rfl
      | step route x y h => exact (hstep route x y h).symm
      | symm _ ih => exact ih.symm
      | trans _ _ ih ih' => exact ih.trans ih'
    · intro hcon route x y h
      exact (hcon x y (PartialRouteGeneratedOrbit.step route x y h)).symm
  have hp : Function.Surjective (partialRouteOrbitQuotient routes) := by
    intro orbit
    induction orbit using Quotient.inductionOn with
    | _ x => exact ⟨x, rfl⟩
  have hcompat : OrbitQuotientCompatible (partialRouteOrbitQuotient routes)
      (PartialRouteGeneratedOrbit routes) := by
    intro x y
    constructor
    · intro h
      exact Quotient.exact h
    · intro h
      exact Quotient.sound h
  exact ⟨hsteps, hsteps.trans
    (conserved_iff_orbit_readout_descends (partialRouteOrbitQuotient routes)
      (PartialRouteGeneratedOrbit routes) quantity hp hcompat)⟩

/-- The total route relation and its invariance predicate are the special
case obtained by wrapping every route output in `some`. -/
theorem total_routes_are_partial_routes
    {X Route V : Type} (routes : Route → X → X) (quantity : X → V) :
    (RouteGeneratorInvariant routes quantity ↔
      PartialRouteGeneratorInvariant (fun route x => some (routes route x))
        quantity) ∧
    (∀ x y, RouteGeneratedOrbit routes x y ↔
      PartialRouteGeneratedOrbit (fun route x => some (routes route x)) x y) := by
  constructor
  · constructor
    · intro h route x y hy
      have hxy : routes route x = y := Option.some.inj hy
      subst y
      exact h route x
    · intro h route x
      exact h route x (routes route x) rfl
  · intro x y
    constructor
    · intro h
      induction h with
      | refl x => exact PartialRouteGeneratedOrbit.refl x
      | step route x =>
          exact PartialRouteGeneratedOrbit.step route x (routes route x) rfl
      | symm _ ih => exact PartialRouteGeneratedOrbit.symm ih
      | trans _ _ ih ih' => exact PartialRouteGeneratedOrbit.trans ih ih'
    · intro h
      induction h with
      | refl x => exact RouteGeneratedOrbit.refl x
      | step route x y hy =>
          have hxy : routes route x = y := Option.some.inj hy
          subst y
          exact RouteGeneratedOrbit.step route x
      | symm _ ih => exact RouteGeneratedOrbit.symm ih
      | trans _ _ ih ih' => exact RouteGeneratedOrbit.trans ih ih'

end SixBirdsMetaMath.FoundationsIV.StatusRecordsCoherence.ConservationAsOrbitDescent
