import SixBirdsMetaMath.FoundationsIV.Transport.DescentRepair

/-!
F31 Counterfactual Legitimacy.

A counterfactual has layer-native truth only when it is generated by a
declared route/intervention package, admissibility is well-defined at the
context/intervention quotient, the route transport descends to the target
quotient, and the target truth predicate descends through that quotient.
-/

namespace SixBirdsMetaMath.FoundationsIV.StatusRecordsCoherence.CounterfactualLegitimacy

open SixBirdsMetaMath.FoundationsIV.Transport.DescentRepair

/-- Quotient of raw context/intervention pairs. -/
def contextRouteQuotient {H Q A Abar : Type} (context : H → Q)
    (intervention : A → Abar) : H × A → Q × Abar :=
  fun pair => (context pair.1, intervention pair.2)

/-- Predicate on raw context/intervention pairs induced by the admissibility
relation. -/
def admissibilityPredicate {H A : Type} (Admissible : H → A → Prop) :
    H × A → Prop :=
  fun pair => Admissible pair.1 pair.2

/-- The carrier of raw pairs on which the counterfactual route is declared. -/
abbrev AdmissiblePair {H A : Type} (Admissible : H → A → Prop) :=
  { pair : H × A // Admissible pair.1 pair.2 }

/-- Quotient of admissible context/intervention pairs. -/
def admissibleContextRouteQuotient {H Q A Abar : Type} (context : H → Q)
    (intervention : A → Abar) (Admissible : H → A → Prop) :
    AdmissiblePair Admissible → Q × Abar :=
  fun pair => (context pair.val.1, intervention pair.val.2)

/-- Raw route transport restricted to admissible pairs. -/
def routeOnAdmissible {H A H' : Type} (route : H → A → H')
    (Admissible : H → A → Prop) : AdmissiblePair Admissible → H' :=
  fun pair => route pair.val.1 pair.val.2

/-- Admissibility must descend through the context/intervention quotient. -/
def AdmissibilityDescends {H Q A Abar : Type} (context : H → Q)
    (intervention : A → Abar) (Admissible : H → A → Prop) : Prop :=
  Descends (contextRouteQuotient context intervention)
    (fun pair : H × A => pair) (admissibilityPredicate Admissible)

/-- Counterfactual transport must descend from admissible pairs to target
quotient values. -/
def CounterfactualTransportDescends {H Q A Abar H' R : Type}
    (context : H → Q) (intervention : A → Abar)
    (Admissible : H → A → Prop) (route : H → A → H') (targetQuotient : H' → R) :
    Prop :=
  Descends (admissibleContextRouteQuotient context intervention Admissible)
    (routeOnAdmissible route Admissible) targetQuotient

/-- Target truth is legitimate at the target layer when it descends through the
target quotient. -/
def TargetTruthDescends {H' R : Type} (targetQuotient : H' → R)
    (targetTruth : H' → Bool) : Prop :=
  Descends targetQuotient (fun x : H' => x) targetTruth

/-- Deterministic counterfactual legitimacy is the three descent gates. -/
def CounterfactualLegitimate {H Q A Abar H' R : Type} (context : H → Q)
    (intervention : A → Abar) (Admissible : H → A → Prop)
    (route : H → A → H') (targetQuotient : H' → R)
    (targetTruth : H' → Bool) : Prop :=
  AdmissibilityDescends context intervention Admissible ∧
    CounterfactualTransportDescends context intervention Admissible route targetQuotient ∧
      TargetTruthDescends targetQuotient targetTruth

/-- Admissibility descent obstruction. -/
def AdmissibilityObstruction {H Q A Abar : Type} (context : H → Q)
    (intervention : A → Abar) (Admissible : H → A → Prop) :
    (H × A) × (H × A) → Prop :=
  splitPairObstruction (contextRouteQuotient context intervention)
    (fun pair : H × A => pair) (admissibilityPredicate Admissible)

/-- No admissibility descent obstruction is present. -/
def AdmissibilityObstructionEmpty {H Q A Abar : Type} (context : H → Q)
    (intervention : A → Abar) (Admissible : H → A → Prop) : Prop :=
  ObstructionEmpty (AdmissibilityObstruction context intervention Admissible)

/-- Counterfactual transport obstruction on admissible raw pairs. -/
def CounterfactualTransportObstruction {H Q A Abar H' R : Type}
    (context : H → Q) (intervention : A → Abar)
    (Admissible : H → A → Prop) (route : H → A → H')
    (targetQuotient : H' → R) :
    (AdmissiblePair Admissible × AdmissiblePair Admissible) → Prop :=
  splitPairObstruction (admissibleContextRouteQuotient context intervention Admissible)
    (routeOnAdmissible route Admissible) targetQuotient

/-- No counterfactual transport obstruction is present. -/
def CounterfactualTransportObstructionEmpty {H Q A Abar H' R : Type}
    (context : H → Q) (intervention : A → Abar)
    (Admissible : H → A → Prop) (route : H → A → H')
    (targetQuotient : H' → R) : Prop :=
  ObstructionEmpty
    (CounterfactualTransportObstruction context intervention Admissible route
      targetQuotient)

/-- Target truth obstruction at the target quotient. -/
def TargetTruthObstruction {H' R : Type} (targetQuotient : H' → R)
    (targetTruth : H' → Bool) : (H' × H') → Prop :=
  splitPairObstruction targetQuotient (fun x : H' => x) targetTruth

/-- No target-truth obstruction is present. -/
def TargetTruthObstructionEmpty {H' R : Type} (targetQuotient : H' → R)
    (targetTruth : H' → Bool) : Prop :=
  ObstructionEmpty (TargetTruthObstruction targetQuotient targetTruth)

/-- Quotient-level deterministic counterfactual verdict. Inadmissible route
classes are not false; they are not evaluable by this verdict. -/
def CounterfactualVerdict {Q Abar R : Type} (AdmissibleBar : Q × Abar → Prop)
    (routeBar : Q × Abar → R) (truthBar : R → Bool) (qa : Q × Abar) : Prop :=
  AdmissibleBar qa ∧ truthBar (routeBar qa) = true

/-- Relational must-counterfactual: all related target quotient values satisfy
the target truth predicate. -/
def MustCounterfactual {Q Abar R : Type} (routeRelation : Q × Abar → R → Prop)
    (truthBar : R → Bool) (qa : Q × Abar) : Prop :=
  ∀ target, routeRelation qa target → truthBar target = true

/-- Relational may-counterfactual: at least one related target quotient value
satisfies the target truth predicate. -/
def MayCounterfactual {Q Abar R : Type} (routeRelation : Q × Abar → R → Prop)
    (truthBar : R → Bool) (qa : Q × Abar) : Prop :=
  ∃ target, routeRelation qa target ∧ truthBar target = true

/-- A probabilistic counterfactual keeps its threshold/status explicit. -/
def ProbabilisticCounterfactual {Q Abar Weight : Type}
    (probability : Q × Abar → Weight) (threshold : Weight)
    (AtLeast : Weight → Weight → Prop) (qa : Q × Abar) : Prop :=
  AtLeast (probability qa) threshold

/-- Source status vocabulary for counterfactual claims. -/
inductive CounterfactualStatus where
  | exactDeterministicCounterfactual
  | mustCounterfactual
  | mayCounterfactual
  | probabilisticCounterfactual
  | inadmissibleCounterfactual
  | admissibilityDescentFailure
  | counterfactualTransportFailure
  | targetTruthDescentFailure
  | routeSpaceAbsent
  | unsupportedAlternative
  | protocolCounterfactual
  | hiddenContextCounterfactual
  | scopedCounterfactual
  | counterfactualOverread
deriving DecidableEq

/-- Meaning assignment for the F31 status vocabulary. -/
def CounterfactualStatusHolds (exact must may probabilistic inadmissible
    admFailure transportFailure targetFailure routeAbsent unsupported protocol hidden
    scopedStatus overread : Prop) : CounterfactualStatus → Prop
  | CounterfactualStatus.exactDeterministicCounterfactual => exact
  | CounterfactualStatus.mustCounterfactual => must
  | CounterfactualStatus.mayCounterfactual => may
  | CounterfactualStatus.probabilisticCounterfactual => probabilistic
  | CounterfactualStatus.inadmissibleCounterfactual => inadmissible
  | CounterfactualStatus.admissibilityDescentFailure => admFailure
  | CounterfactualStatus.counterfactualTransportFailure => transportFailure
  | CounterfactualStatus.targetTruthDescentFailure => targetFailure
  | CounterfactualStatus.routeSpaceAbsent => routeAbsent
  | CounterfactualStatus.unsupportedAlternative => unsupported
  | CounterfactualStatus.protocolCounterfactual => protocol
  | CounterfactualStatus.hiddenContextCounterfactual => hidden
  | CounterfactualStatus.scopedCounterfactual => scopedStatus
  | CounterfactualStatus.counterfactualOverread => overread

/-- Admissibility descends iff there is no admissibility obstruction. -/
theorem admissibility_descends_iff_no_obstruction {H Q A Abar : Type}
    (context : H → Q) (intervention : A → Abar) (Admissible : H → A → Prop)
    (hcontextRoute :
      Function.Surjective (contextRouteQuotient context intervention)) :
    AdmissibilityDescends context intervention Admissible ↔
      AdmissibilityObstructionEmpty context intervention Admissible :=
  descent_repair_normal_form (contextRouteQuotient context intervention)
    (fun pair : H × A => pair) (admissibilityPredicate Admissible) hcontextRoute

/-- Counterfactual transport descends iff no admissible same-context/route pair
splits the target quotient. -/
theorem transport_descends_iff_no_obstruction {H Q A Abar H' R : Type}
    (context : H → Q) (intervention : A → Abar)
    (Admissible : H → A → Prop) (route : H → A → H')
    (targetQuotient : H' → R)
    (hadmissibleContextRoute :
      Function.Surjective (admissibleContextRouteQuotient context intervention
        Admissible)) :
    CounterfactualTransportDescends context intervention Admissible route
        targetQuotient ↔
      CounterfactualTransportObstructionEmpty context intervention Admissible route
        targetQuotient :=
  descent_repair_normal_form
    (admissibleContextRouteQuotient context intervention Admissible)
    (routeOnAdmissible route Admissible) targetQuotient hadmissibleContextRoute

/-- Target truth descends iff there is no target-truth obstruction. -/
theorem target_truth_descends_iff_no_obstruction {H' R : Type}
    (targetQuotient : H' → R) (targetTruth : H' → Bool)
    (htargetQuotient : Function.Surjective targetQuotient) :
    TargetTruthDescends targetQuotient targetTruth ↔
      TargetTruthObstructionEmpty targetQuotient targetTruth :=
  descent_repair_normal_form targetQuotient (fun x : H' => x) targetTruth
    htargetQuotient

/-- Deterministic counterfactual legitimacy is exactly the three empty
obstruction conditions. -/
theorem legitimate_iff_empty_obstructions {H Q A Abar H' R : Type}
    (context : H → Q) (intervention : A → Abar)
    (Admissible : H → A → Prop) (route : H → A → H')
    (targetQuotient : H' → R) (targetTruth : H' → Bool)
    (hcontextRoute :
      Function.Surjective (contextRouteQuotient context intervention))
    (hadmissibleContextRoute :
      Function.Surjective (admissibleContextRouteQuotient context intervention
        Admissible))
    (htargetQuotient : Function.Surjective targetQuotient) :
    CounterfactualLegitimate context intervention Admissible route targetQuotient
        targetTruth ↔
      AdmissibilityObstructionEmpty context intervention Admissible ∧
        CounterfactualTransportObstructionEmpty context intervention Admissible route
          targetQuotient ∧
          TargetTruthObstructionEmpty targetQuotient targetTruth := by
  constructor
  · intro hlegit
    exact ⟨(admissibility_descends_iff_no_obstruction context intervention
        Admissible hcontextRoute).1 hlegit.1,
      (transport_descends_iff_no_obstruction context intervention Admissible route
        targetQuotient hadmissibleContextRoute).1 hlegit.2.1,
      (target_truth_descends_iff_no_obstruction targetQuotient targetTruth
        htargetQuotient).1 hlegit.2.2⟩
  · intro hclear
    exact ⟨(admissibility_descends_iff_no_obstruction context intervention
        Admissible hcontextRoute).2 hclear.1,
      (transport_descends_iff_no_obstruction context intervention Admissible route
        targetQuotient hadmissibleContextRoute).2 hclear.2.1,
      (target_truth_descends_iff_no_obstruction targetQuotient targetTruth
        htargetQuotient).2 hclear.2.2⟩

/-- Equivalent quotient-level factorization form of deterministic
counterfactual legitimacy. -/
theorem legitimate_iff_quotient_factorization {H Q A Abar H' R : Type}
    (context : H → Q) (intervention : A → Abar)
    (Admissible : H → A → Prop) (route : H → A → H')
    (targetQuotient : H' → R) (targetTruth : H' → Bool) :
    CounterfactualLegitimate context intervention Admissible route targetQuotient
        targetTruth ↔
      ∃ AdmissibleBar : Q × Abar → Prop, ∃ routeBar : Q × Abar → R,
        ∃ truthBar : R → Bool,
          AdmissibleBar ∘ contextRouteQuotient context intervention =
            admissibilityPredicate Admissible ∧
          routeBar ∘ admissibleContextRouteQuotient context intervention
              Admissible =
            targetQuotient ∘ routeOnAdmissible route Admissible ∧
          truthBar ∘ targetQuotient = targetTruth := by
  constructor
  · intro hlegit
    rcases hlegit.1 with ⟨AdmissibleBar, hAdmissibleBar⟩
    rcases hlegit.2.1 with ⟨routeBar, hrouteBar⟩
    rcases hlegit.2.2 with ⟨truthBar, htruthBar⟩
    exact ⟨AdmissibleBar, routeBar, truthBar, hAdmissibleBar, hrouteBar,
      htruthBar⟩
  · intro hfactor
    rcases hfactor with
      ⟨AdmissibleBar, routeBar, truthBar, hAdmissibleBar, hrouteBar, htruthBar⟩
    exact ⟨⟨AdmissibleBar, hAdmissibleBar⟩,
      ⟨routeBar, hrouteBar⟩, ⟨truthBar, htruthBar⟩⟩

/-- May and must are not collapsed: must gives may only when the descended
route relation has a witness. -/
theorem must_counterfactual_with_witness_implies_may {Q Abar R : Type}
    (routeRelation : Q × Abar → R → Prop) (truthBar : R → Bool)
    (qa : Q × Abar) :
    MustCounterfactual routeRelation truthBar qa →
      (∃ target, routeRelation qa target) →
        MayCounterfactual routeRelation truthBar qa := by
  intro hmust hwitness
  rcases hwitness with ⟨target, hroute⟩
  exact ⟨target, hroute, hmust target hroute⟩

/-- Probabilistic counterfactual status is thresholded explicitly and is not
asserted as deterministic exact truth. -/
theorem probabilistic_counterfactual_has_probabilistic_status {Q Abar Weight : Type}
    (probability : Q × Abar → Weight) (threshold : Weight)
    (AtLeast : Weight → Weight → Prop) (qa : Q × Abar) :
    ProbabilisticCounterfactual probability threshold AtLeast qa →
      CounterfactualStatusHolds False False False True False False False False False
        False False False False False CounterfactualStatus.probabilisticCounterfactual := by
  intro _
  trivial

/--
Counterfactual Legitimacy Normal Form. A deterministic counterfactual is
legitimate exactly when admissibility, admissible route transport, and target
truth all descend through their declared quotients; equivalently, quotient-
level admissibility, route, and truth maps exist.
-/
theorem counterfactual_legitimacy {H Q A Abar H' R : Type}
    (context : H → Q) (intervention : A → Abar)
    (Admissible : H → A → Prop) (route : H → A → H')
    (targetQuotient : H' → R) (targetTruth : H' → Bool)
    (hcontextRoute :
      Function.Surjective (contextRouteQuotient context intervention))
    (hadmissibleContextRoute :
      Function.Surjective (admissibleContextRouteQuotient context intervention
        Admissible))
    (htargetQuotient : Function.Surjective targetQuotient) :
    (CounterfactualLegitimate context intervention Admissible route targetQuotient
        targetTruth ↔
      AdmissibilityObstructionEmpty context intervention Admissible ∧
        CounterfactualTransportObstructionEmpty context intervention Admissible route
          targetQuotient ∧
          TargetTruthObstructionEmpty targetQuotient targetTruth) ∧
      (CounterfactualLegitimate context intervention Admissible route targetQuotient
          targetTruth ↔
        ∃ AdmissibleBar : Q × Abar → Prop, ∃ routeBar : Q × Abar → R,
          ∃ truthBar : R → Bool,
            AdmissibleBar ∘ contextRouteQuotient context intervention =
              admissibilityPredicate Admissible ∧
            routeBar ∘ admissibleContextRouteQuotient context intervention
                Admissible =
              targetQuotient ∘ routeOnAdmissible route Admissible ∧
            truthBar ∘ targetQuotient = targetTruth) := by
  exact ⟨legitimate_iff_empty_obstructions context intervention Admissible route
      targetQuotient targetTruth hcontextRoute hadmissibleContextRoute htargetQuotient,
    legitimate_iff_quotient_factorization context intervention Admissible route
      targetQuotient targetTruth⟩


/-- Paper admissibility obstruction on raw context/intervention pairs. -/
def PaperAdmObstruction {H Q A Abar : Type} (q : H → Q)
    (α : A → Abar) (Adm : H → A → Prop) (z : (H × A) × (H × A)) : Prop :=
  q z.1.1 = q z.2.1 ∧ α z.1.2 = α z.2.2 ∧
    ¬ (Adm z.1.1 z.1.2 ↔ Adm z.2.1 z.2.2)

/-- Paper truth obstruction restricted to admissible pairs. -/
def PaperCFObstruction {H Q A Abar H' : Type} (q : H → Q)
    (α : A → Abar) (Adm : H → A → Prop) (Γ : H → A → H')
    (τ : H' → Bool) (z : (H × A) × (H × A)) : Prop :=
  q z.1.1 = q z.2.1 ∧ α z.1.2 = α z.2.2 ∧
    Adm z.1.1 z.1.2 ∧ Adm z.2.1 z.2.2 ∧
      τ (Γ z.1.1 z.1.2) ≠ τ (Γ z.2.1 z.2.2)

/-- Counterfactual legitimacy is classwise admissibility and admissible truth constancy. -/
def PaperCFL {H Q A Abar H' : Type} (q : H → Q)
    (α : A → Abar) (Adm : H → A → Prop) (Γ : H → A → H')
    (τ : H' → Bool) : Prop :=
  (∀ h a h' a', q h = q h' → α a = α a' →
    (Adm h a ↔ Adm h' a')) ∧
  (∀ h a h' a', q h = q h' → α a = α a' →
    Adm h a → Adm h' a' → τ (Γ h a) = τ (Γ h' a'))

/-- The repaired paper equivalences; surjectivity fills every quotient class. -/
theorem paper_counterfactual_legitimacy {H Q A Abar H' R : Type}
    (q : H → Q) (α : A → Abar) (Adm : H → A → Prop)
    (Γ : H → A → H') (_q' : H' → R) (τ : H' → Bool)
    (hq : Function.Surjective q) (hα : Function.Surjective α) :
    (PaperCFL q α Adm Γ τ ↔
      (∀ z, ¬ PaperAdmObstruction q α Adm z) ∧
      (∀ z, ¬ PaperCFObstruction q α Adm Γ τ z)) ∧
    (PaperCFL q α Adm Γ τ ↔
      ∃ Admbar : Q × Abar → Prop, ∃ τbar : Q × Abar → Bool,
        (∀ h a, Admbar (q h, α a) ↔ Adm h a) ∧
        (∀ h a, Adm h a → τbar (q h, α a) = τ (Γ h a))) := by
  classical
  have hobs : PaperCFL q α Adm Γ τ ↔
      (∀ z, ¬ PaperAdmObstruction q α Adm z) ∧
      (∀ z, ¬ PaperCFObstruction q α Adm Γ τ z) := by
    constructor
    · rintro ⟨ha,ht⟩
      constructor
      · rintro ⟨⟨h,a⟩,⟨h',a'⟩⟩ ⟨hq',hα',hne⟩
        exact hne (ha h a h' a' hq' hα')
      · rintro ⟨⟨h,a⟩,⟨h',a'⟩⟩ ⟨hq',hα',hadm,hadm',hne⟩
        exact hne (ht h a h' a' hq' hα' hadm hadm')
    · rintro ⟨ha,ht⟩
      constructor
      · intro h a h' a' hq' hα'
        exact Classical.byContradiction (fun hne =>
          ha ((h,a),(h',a')) ⟨hq',hα',hne⟩)
      · intro h a h' a' hq' hα' hadm hadm'
        exact Classical.byContradiction (fun hne =>
          ht ((h,a),(h',a')) ⟨hq',hα',hadm,hadm',hne⟩)
  refine ⟨hobs, ?_⟩
  constructor
  · rintro ⟨ha,ht⟩
    let rep : Q × Abar → H × A := fun z =>
      (Classical.choose (hq z.1), Classical.choose (hα z.2))
    have hrep (z : Q × Abar) : (q (rep z).1, α (rep z).2) = z := by
      apply Prod.ext
      · exact Classical.choose_spec (hq z.1)
      · exact Classical.choose_spec (hα z.2)
    refine ⟨fun z => Adm (rep z).1 (rep z).2,
      fun z => τ (Γ (rep z).1 (rep z).2), ?_, ?_⟩
    · intro h a
      have hz := hrep (q h, α a)
      exact ha (rep (q h, α a)).1 (rep (q h, α a)).2 h a
        (congrArg Prod.fst hz) (congrArg Prod.snd hz)
    · intro h a hadm
      have hz := hrep (q h, α a)
      exact ht (rep (q h, α a)).1 (rep (q h, α a)).2 h a
        (congrArg Prod.fst hz) (congrArg Prod.snd hz)
        ((ha (rep (q h, α a)).1 (rep (q h, α a)).2 h a
          (congrArg Prod.fst hz) (congrArg Prod.snd hz)).2 hadm) hadm
  · rintro ⟨Admbar,τbar,ha,ht⟩
    constructor
    · intro h a h' a' hq' hα'
      calc
        Adm h a ↔ Admbar (q h, α a) := (ha h a).symm
        _ ↔ Admbar (q h', α a') := by rw [hq', hα']
        _ ↔ Adm h' a' := ha h' a'
    · intro h a h' a' hq' hα' hadm hadm'
      calc
        τ (Γ h a) = τbar (q h, α a) := (ht h a hadm).symm
        _ = τbar (q h', α a') := by rw [hq', hα']
        _ = τ (Γ h' a') := ht h' a' hadm'


/-- Prop-valued admissibility and Bool-valued truth admit defaults outside
the quotient image, so neither context nor intervention surjectivity is needed. -/
theorem paper_counterfactual_legitimacy_without_surjectivity {H Q A Abar H' R : Type}
    (q : H → Q) (α : A → Abar) (Adm : H → A → Prop)
    (Γ : H → A → H') (_q' : H' → R) (τ : H' → Bool) :
    (PaperCFL q α Adm Γ τ ↔
      (∀ z, ¬ PaperAdmObstruction q α Adm z) ∧
      (∀ z, ¬ PaperCFObstruction q α Adm Γ τ z)) ∧
    (PaperCFL q α Adm Γ τ ↔
      ∃ Admbar : Q × Abar → Prop, ∃ τbar : Q × Abar → Bool,
        (∀ h a, Admbar (q h, α a) ↔ Adm h a) ∧
        (∀ h a, Adm h a → τbar (q h, α a) = τ (Γ h a))) := by
  classical
  have hobs : PaperCFL q α Adm Γ τ ↔
      (∀ z, ¬ PaperAdmObstruction q α Adm z) ∧
      (∀ z, ¬ PaperCFObstruction q α Adm Γ τ z) := by
    constructor
    · rintro ⟨ha,ht⟩
      constructor
      · rintro ⟨⟨h,a⟩,⟨h',a'⟩⟩ ⟨hq',hα',hne⟩
        exact hne (ha h a h' a' hq' hα')
      · rintro ⟨⟨h,a⟩,⟨h',a'⟩⟩ ⟨hq',hα',hadm,hadm',hne⟩
        exact hne (ht h a h' a' hq' hα' hadm hadm')
    · rintro ⟨ha,ht⟩
      constructor
      · intro h a h' a' hq' hα'
        exact Classical.byContradiction (fun hne =>
          ha ((h,a),(h',a')) ⟨hq',hα',hne⟩)
      · intro h a h' a' hq' hα' hadm hadm'
        exact Classical.byContradiction (fun hne =>
          ht ((h,a),(h',a')) ⟨hq',hα',hadm,hadm',hne⟩)
  refine ⟨hobs, ?_⟩
  constructor
  · rintro ⟨ha, ht⟩
    let Admbar : Q × Abar → Prop := fun z =>
      ∃ h a, (q h, α a) = z ∧ Adm h a
    let τbar : Q × Abar → Bool := fun z =>
      if hz : ∃ p : H × A, (q p.1, α p.2) = z ∧ Adm p.1 p.2 then
        τ (Γ (Classical.choose hz).1 (Classical.choose hz).2)
      else false
    refine ⟨Admbar, τbar, ?_, ?_⟩
    · intro h a
      constructor
      · rintro ⟨h', a', heq, hadm⟩
        exact (ha h' a' h a (congrArg Prod.fst heq)
          (congrArg Prod.snd heq)).mp hadm
      · intro hadm
        exact ⟨h, a, rfl, hadm⟩
    · intro h a hadm
      have hz : ∃ p : H × A, (q p.1, α p.2) = (q h, α a) ∧ Adm p.1 p.2 :=
        ⟨(h, a), rfl, hadm⟩
      dsimp only [τbar]
      rw [dif_pos hz]
      have hp := Classical.choose_spec hz
      exact ht (Classical.choose hz).1 (Classical.choose hz).2 h a
        (congrArg Prod.fst hp.1) (congrArg Prod.snd hp.1) hp.2 hadm
  · rintro ⟨Admbar,τbar,ha,ht⟩
    constructor
    · intro h a h' a' hq' hα'
      calc
        Adm h a ↔ Admbar (q h, α a) := (ha h a).symm
        _ ↔ Admbar (q h', α a') := by rw [hq', hα']
        _ ↔ Adm h' a' := ha h' a'
    · intro h a h' a' hq' hα' hadm hadm'
      calc
        τ (Γ h a) = τbar (q h, α a) := (ht h a hadm).symm
        _ = τbar (q h', α a') := by rw [hq', hα']
        _ = τ (Γ h' a') := ht h' a' hadm'

end SixBirdsMetaMath.FoundationsIV.StatusRecordsCoherence.CounterfactualLegitimacy
