import SixBirdsMetaMath.Terminology
import SixBirdsMetaMath.AOR.ResidualAtlas

namespace SixBirdsMetaMath.AOR.Cascades

open SixBirdsMetaMath.AOR.PreSB
open SixBirdsMetaMath.AOR.ResidualAtlas

universe u

/-!
This retained adapter is synchronized with the maintained Needles version.
References below to semantic AOR modules absent from this namespace mean
`SixBirdsNeedles.AOR.*`; this module does not re-export those endpoints.

Legacy tag/cost-table representation. Its syntactic cascade theorems do not
prove termination or confluence of arbitrary evidence-producing operations.
The revised endpoints are `OperationCascade.terminates_of_progress`,
`OperationConfluence.confluence` and `OperationalHierarchy.strict_hierarchy`.
They include fresh work, legal inputs and the necessary progress/replay or
uniform-cost hypotheses. The original status vocabulary is retained here for
use by the typed payload adapter.


AOR paper §6 "Discharge cascades over Sigma_residual".

This module hosts the cost table, cascade graph, and cascade theorems:
- `def:aor:cost-record`                       — `(type, status) ↦ Multiset(type, status)`
- `def:aor:down-operator`                     — downstream-obligation operator
- `def:aor:cost-table`                        — 132-entry cost table (12 types × 11 statuses)
- `def:aor:cascade-graph`                     — bipartite cascade graph
- `thm:aor:cascade-bipartite`                 — bipartite structure theorem
- `thm:aor:cascade-termination`               — well-founded (status-decreasing measure)
- `thm:aor:cascade-confluence`                — local + global confluence (Newman)
- `thm:aor:cross-cascade-composition`         — composition over carrier products
- `def:aor:cascade-stable-aor`                — `CascadeStableAOR ⊊ AOR`
- `thm:aor:cascade-stable-characterisation`   — characterisation via `omega`-iteration

Statements are paper-grounded against `paper/aor/aor_paper.tex` §6.
The finite cost table is realized as a `List`-valued function, and the
cascade graph is an inductive labelled-edge predicate. No project-local
postulates.
-/

/-- The base AOR-8 status catalogue used by the cascade cost table. -/
inductive AOR8Status where
  | zero
  | budgeted
  | bridged
  | hidden
  | moduli
  | selected
  | probabilistic
  | outOfScope
  | nonclaim
  | blocked
  | approvedOther

/-- Status rank for the paid-strictness component of the cascade measure. -/
def statusRank : AOR8Status → Nat
  | AOR8Status.zero => 0
  | AOR8Status.approvedOther => 1
  | AOR8Status.budgeted => 2
  | AOR8Status.bridged => 3
  | AOR8Status.hidden => 4
  | AOR8Status.moduli => 5
  | AOR8Status.selected => 6
  | AOR8Status.probabilistic => 7
  | AOR8Status.nonclaim => 8
  | AOR8Status.blocked => 9
  | AOR8Status.outOfScope => 10

/-- Residual-type rank for the forced-residual-depth component. -/
def residualTypeRank (t : residualTypesTwelve) : Nat :=
  (forcedSecondaryTypes t).length

/--
`def:aor:cost-record`.

A cost record is the finite list of downstream residual/status obligations
generated by paying one atom of primary type `residualType` with `status`.
-/
structure CostRecord where
  residualType : residualTypesTwelve
  status : AOR8Status
  downstream : List (residualTypesTwelve × AOR8Status)

/-- Cost obligations generated by one residual/status pair. -/
def costRecord (t : residualTypesTwelve) (s : AOR8Status) : CostRecord where
  residualType := t
  status := s
  downstream :=
    match t, s with
    | SixBirdsMetaMath.AOR.DefectStrata.residualTypesTwelve.transport, AOR8Status.blocked =>
        [(SixBirdsMetaMath.AOR.DefectStrata.residualTypesTwelve.transport, AOR8Status.budgeted),
          (SixBirdsMetaMath.AOR.DefectStrata.residualTypesTwelve.role, AOR8Status.zero)]
    | SixBirdsMetaMath.AOR.DefectStrata.residualTypesTwelve.source, AOR8Status.budgeted =>
        [(SixBirdsMetaMath.AOR.DefectStrata.residualTypesTwelve.transport, AOR8Status.zero),
          (SixBirdsMetaMath.AOR.DefectStrata.residualTypesTwelve.scale, AOR8Status.zero),
          (SixBirdsMetaMath.AOR.DefectStrata.residualTypesTwelve.target, AOR8Status.zero),
          (SixBirdsMetaMath.AOR.DefectStrata.residualTypesTwelve.role, AOR8Status.zero)]
    | SixBirdsMetaMath.AOR.DefectStrata.residualTypesTwelve.scale, AOR8Status.hidden =>
        [(SixBirdsMetaMath.AOR.DefectStrata.residualTypesTwelve.scale, AOR8Status.blocked)]
    | _, AOR8Status.zero => []
    | _, AOR8Status.approvedOther => []
    | _, _ => (t, AOR8Status.zero) :: (forcedSecondaryTypes t).map (fun t' => (t', AOR8Status.zero))

/--
`def:aor:cost-table`.

The cost table is the total finite table function from residual/status pairs
to downstream obligations.  This definition explicitly enumerates the §6 rows
`(transport, blocked)`, `(source, budgeted)`, and `(scale, hidden)`.
Asymptotic limit-status rows live in
`SixBirdsMetaMath.AOR.Refinement.asymptoticCostTable`, keeping the base AOR-8
catalogue separate from the four asymptotic statuses. Rows not yet enumerated
by this definition-metadata slice fall back to a self-zero obligation plus the
forced secondary types as zero-status obligations.
-/
def costTable (t : residualTypesTwelve) (s : AOR8Status) :
    List (residualTypesTwelve × AOR8Status) :=
  (costRecord t s).downstream

/--
`def:aor:discharge-record`.

A discharge record on a residual atom is a triple `(atom, status, witness)`
with a typed `witness_holds` payload appropriate to the chosen AOR-8 status.
-/
structure DischargeWitness where
  atom : ResidualRecord
  status : AOR8Status
  witness : Prop
  witness_holds : witness

/--
`def:aor:discharge-witness`.

A discharge witness for a residual record is a family of discharge records,
one per atom in its decomposition. The list closes the record when every
status is from the AOR-8 catalogue (or its asymptotic extensions) and every
forced-secondary type also has a discharge record in the family.
-/
abbrev DischargeWitnessFamily : Type := List DischargeWitness

/-- Append the downstream obligations generated by a list of witnesses. -/
def downstreamObligations : List DischargeWitness → List (residualTypesTwelve × AOR8Status)
  | [] => []
  | w :: ws => costTable w.atom.primary w.status ++ downstreamObligations ws

/--
`def:aor:down-operator`.

`Down` collects the cost-table rows generated by a residual record's discharge
witnesses and packages the fresh downstream atom types as the secondary field
of a new residual record.
-/
def downOperator (r : ResidualRecord) (witnesses : List DischargeWitness) :
    ResidualRecord where
  primary := r.primary
  secondary := (downstreamObligations witnesses).map Prod.fst
  refinementDepth := r.refinementDepth.pred

/-- Vertices of the cascade graph alternate between atoms and witnesses. -/
inductive CascadeVertex where
  | atom : ResidualRecord → CascadeVertex
  | witness : DischargeWitness → CascadeVertex

/-- The kind of a cascade vertex. -/
inductive CascadeVertexKind where
  | atom
  | witness

/-- Vertex-kind projection. -/
def cascadeVertexKind : CascadeVertex → CascadeVertexKind
  | CascadeVertex.atom _ => CascadeVertexKind.atom
  | CascadeVertex.witness _ => CascadeVertexKind.witness

/-- Labelled cascade edges generated by the downstream operator. -/
inductive CascadeEdge (r : ResidualRecord) (witnesses : List DischargeWitness) :
    CascadeVertex → CascadeVertex → AOR8Status → Prop where
  | atomToWitness (w : DischargeWitness) :
      List.Mem w witnesses →
        CascadeEdge r witnesses (CascadeVertex.atom r) (CascadeVertex.witness w) w.status
  | witnessToAtom (w : DischargeWitness) (t : residualTypesTwelve) (s : AOR8Status) :
      List.Mem w witnesses →
        List.Mem (t, s) (costTable w.atom.primary w.status) →
          CascadeEdge r witnesses (CascadeVertex.witness w)
            (CascadeVertex.atom { primary := t, secondary := [], refinementDepth := 0 }) s

/--
`def:aor:cascade-graph`.

The cascade graph is the labelled edge predicate whose vertices are residual
atoms and discharge witnesses and whose edges are produced by `Down`.
-/
structure CascadeGraph where
  seed : ResidualRecord
  witnesses : List DischargeWitness
  edge : CascadeVertex → CascadeVertex → AOR8Status → Prop

/-- The cascade graph generated by a residual record and discharge witnesses. -/
def cascadeGraph (r : ResidualRecord) (witnesses : List DischargeWitness) : CascadeGraph where
  seed := r
  witnesses := witnesses
  edge := CascadeEdge r witnesses

/-- An edge alternates between atom and witness vertex kinds. -/
def edgeAlternates (source target : CascadeVertex) : Prop :=
  (cascadeVertexKind source = CascadeVertexKind.atom ∧
      cascadeVertexKind target = CascadeVertexKind.witness) ∨
    (cascadeVertexKind source = CascadeVertexKind.witness ∧
      cascadeVertexKind target = CascadeVertexKind.atom)

/-- Proof package for the bipartite cascade graph theorem. -/
structure CascadeBipartiteWitness (r : ResidualRecord)
    (witnesses : List DischargeWitness) : Prop where
  edges_alternate :
    ∀ source target status,
      (cascadeGraph r witnesses).edge source target status → edgeAlternates source target
  no_same_kind :
    ∀ source target status,
      (cascadeGraph r witnesses).edge source target status →
        cascadeVertexKind source ≠ cascadeVertexKind target

/--
`thm:aor:cascade-bipartite`.

Every edge in `G(r)` goes from an atom vertex to a witness vertex, or from a
witness vertex to a downstream atom vertex; hence no edge joins two vertices
of the same kind.
-/
theorem cascadeBipartite (r : ResidualRecord) (witnesses : List DischargeWitness) :
    CascadeBipartiteWitness r witnesses where
  edges_alternate := by
    intro source target status h
    cases h with
    | atomToWitness w hw =>
        exact Or.inl ⟨rfl, rfl⟩
    | witnessToAtom w t s hw hcost =>
        exact Or.inr ⟨rfl, rfl⟩
  no_same_kind := by
    intro source target status h
    cases h with
    | atomToWitness w hw =>
        intro hsame
        cases hsame
    | witnessToAtom w t s hw hcost =>
        intro hsame
        cases hsame

/-- Lexicographic cascade measure. -/
def cascadeMeasure (t : residualTypesTwelve) (s : AOR8Status) : Nat × Nat :=
  (residualTypeRank t, statusRank s)

/-- A finite upper bound for the cascade generated by the selected witnesses. -/
def cascadeStepBound (_r : ResidualRecord) (witnesses : List DischargeWitness) : Nat :=
  witnesses.length + (downstreamObligations witnesses).length

/--
The normalized target of one discharge step.

The graph-level `Down` operator still records the cost-table obligations in
the secondary field.  The step relation used for termination and confluence
models the normalizing discharge step: once the selected witnesses are paid,
the current refinement layer is removed.
-/
def dischargeStepTarget (r : ResidualRecord) (_witnesses : List DischargeWitness) :
    ResidualRecord where
  primary := r.primary
  secondary := []
  refinementDepth := r.refinementDepth.pred

/-- One normalized discharge step, using the selected witnesses. -/
inductive DischargeStep : ResidualRecord → ResidualRecord → Prop where
  | step (r : ResidualRecord) (witnesses : List DischargeWitness) :
      0 < r.refinementDepth → DischargeStep r (dischargeStepTarget r witnesses)

/-- The converse orientation of one-step discharge, used by well-foundedness. -/
def dischargeStepRelation (after before : ResidualRecord) : Prop :=
  DischargeStep before after

/-- The ambient depth relation that bounds discharge steps. -/
def dischargeDepthRelation (after before : ResidualRecord) : Prop :=
  after.refinementDepth < before.refinementDepth

/-- The ambient depth relation is well-founded by the natural-number measure. -/
theorem dischargeDepthRelation_wf : WellFounded dischargeDepthRelation := by
  simpa [dischargeDepthRelation] using
    (measure (fun r : ResidualRecord => r.refinementDepth)).wf

/-- Every one-step discharge strictly decreases refinement depth. -/
theorem dischargeStep_decreases {r₁ r₂ : ResidualRecord} (h : DischargeStep r₁ r₂) :
    r₂.refinementDepth < r₁.refinementDepth := by
  cases h with
  | step witnesses hpos =>
      exact Nat.pred_lt (Nat.ne_of_gt hpos)

/-- The normalized discharge relation is well-founded. -/
theorem dischargeStepWellFounded : WellFounded dischargeStepRelation :=
  Subrelation.wf (by
    intro after before h
    exact dischargeStep_decreases h) dischargeDepthRelation_wf

/-- Proof package for cascade termination. -/
structure CascadeTerminationWitness (r : ResidualRecord)
    (witnesses : List DischargeWitness) : Prop where
  measure_defined : ∀ t s, cascadeMeasure t s = (residualTypeRank t, statusRank s)
  finite_bound : ∃ n, n = cascadeStepBound r witnesses
  measure_decreases : ∀ {r₁ r₂ : ResidualRecord}, DischargeStep r₁ r₂ →
    r₂.refinementDepth < r₁.refinementDepth
  terminates_finitely : WellFounded dischargeStepRelation

/--
`thm:aor:cascade-termination`.

The cascade measure is the pair `(rank(type), rank(status))`; the concrete
finite graph has a finite bound given by its selected witness and downstream
obligation lists.  The one-step discharge relation is well-founded because
each step strictly lowers the residual refinement depth.
-/
theorem cascadeTermination (r : ResidualRecord) (witnesses : List DischargeWitness) :
    CascadeTerminationWitness r witnesses where
  measure_defined := by
    intro t s
    rfl
  finite_bound := ⟨cascadeStepBound r witnesses, rfl⟩
  measure_decreases := by
    intro r₁ r₂ h
    exact dischargeStep_decreases h
  terminates_finitely := dischargeStepWellFounded

/-- Reflexive-transitive discharge reachability, represented with a finite step count. -/
inductive DischargeReachable : ResidualRecord → ResidualRecord → Nat → Prop where
  | refl (r : ResidualRecord) : DischargeReachable r r 0
  | step {r₁ r₂ r₃ : ResidualRecord} {n : Nat} :
      DischargeStep r₁ r₂ → DischargeReachable r₂ r₃ n →
        DischargeReachable r₁ r₃ (n + 1)

/--
Proof package for cascade confluence.

This package contains the local-confluence diamond and well-founded one-step
relation. The full Newman implication and unique normal form are now proved
separately in `AOR.Confluence`, avoiding a circular import here.
-/
structure CascadeConfluenceWitness : Prop where
  locally_confluent :
    ∀ a r₁ r₂, DischargeStep a r₁ → DischargeStep a r₂ →
      ∃ r₃ n₁ n₂, DischargeReachable r₁ r₃ n₁ ∧ DischargeReachable r₂ r₃ n₂
  terminating_relation : WellFounded dischargeStepRelation

/--
`thm:aor:cascade-confluence`.

Local confluence is witnessed by the deterministic normalized target of any
one-step discharge.  Together with `dischargeStepWellFounded`, this is the
local package. The full global-confluence induction is exported by
`Confluence.legacy_global_confluence` for this same normalized relation.
-/
theorem cascadeConfluence : CascadeConfluenceWitness where
  locally_confluent := by
    intro a r₁ r₂ h₁ h₂
    cases h₁ with
    | step witnesses₁ hpos₁ =>
        cases h₂ with
        | step witnesses₂ hpos₂ =>
            exact ⟨dischargeStepTarget a witnesses₁, 0, 0,
              DischargeReachable.refl (dischargeStepTarget a witnesses₁),
              DischargeReachable.refl (dischargeStepTarget a witnesses₂)⟩
  terminating_relation := dischargeStepWellFounded

/-- Cross edges are exactly the four product-interaction primary types. -/
inductive CrossCascadeEdge (r₁ r₂ : ResidualRecord) where
  | interface : CrossCascadeEdge r₁ r₂
  | local : CrossCascadeEdge r₁ r₂
  | global : CrossCascadeEdge r₁ r₂
  | sym : CrossCascadeEdge r₁ r₂

/-- The primary residual type attached to a cross-cascade edge. -/
def crossCascadeEdgePrimary {r₁ r₂ : ResidualRecord} :
    CrossCascadeEdge r₁ r₂ → residualTypesTwelve
  | CrossCascadeEdge.interface => SixBirdsMetaMath.AOR.DefectStrata.residualTypesTwelve.interface
  | CrossCascadeEdge.local => SixBirdsMetaMath.AOR.DefectStrata.residualTypesTwelve.local
  | CrossCascadeEdge.global => SixBirdsMetaMath.AOR.DefectStrata.residualTypesTwelve.global
  | CrossCascadeEdge.sym => SixBirdsMetaMath.AOR.DefectStrata.residualTypesTwelve.sym

/-- Disjoint union of two residual records on the same carrier. -/
def disjointUnionResidual (r₁ r₂ : ResidualRecord) : ResidualRecord where
  primary := r₁.primary
  secondary := r₁.secondary ++ r₂.secondary
  refinementDepth := r₁.refinementDepth + r₂.refinementDepth

/-- Edge classes in a disjoint-union cascade. -/
inductive DisjointUnionEdgeClass (r₁ r₂ : ResidualRecord)
    (witnesses₁ witnesses₂ : List DischargeWitness) :
    CascadeVertex → CascadeVertex → AOR8Status → Prop where
  | leftAtomToWitness (w : DischargeWitness) :
      List.Mem w witnesses₁ →
        DisjointUnionEdgeClass r₁ r₂ witnesses₁ witnesses₂
          (CascadeVertex.atom (disjointUnionResidual r₁ r₂)) (CascadeVertex.witness w) w.status
  | rightAtomToWitness (w : DischargeWitness) :
      List.Mem w witnesses₂ →
        DisjointUnionEdgeClass r₁ r₂ witnesses₁ witnesses₂
          (CascadeVertex.atom (disjointUnionResidual r₁ r₂)) (CascadeVertex.witness w) w.status
  | leftWitnessToAtom (w : DischargeWitness) (t : residualTypesTwelve) (s : AOR8Status) :
      List.Mem w witnesses₁ →
        List.Mem (t, s) (costTable w.atom.primary w.status) →
          DisjointUnionEdgeClass r₁ r₂ witnesses₁ witnesses₂ (CascadeVertex.witness w)
            (CascadeVertex.atom { primary := t, secondary := [], refinementDepth := 0 }) s
  | rightWitnessToAtom (w : DischargeWitness) (t : residualTypesTwelve) (s : AOR8Status) :
      List.Mem w witnesses₂ →
        List.Mem (t, s) (costTable w.atom.primary w.status) →
          DisjointUnionEdgeClass r₁ r₂ witnesses₁ witnesses₂ (CascadeVertex.witness w)
            (CascadeVertex.atom { primary := t, secondary := [], refinementDepth := 0 }) s
  | cross (e : CrossCascadeEdge r₁ r₂) :
      DisjointUnionEdgeClass r₁ r₂ witnesses₁ witnesses₂
        (CascadeVertex.atom r₁) (CascadeVertex.atom r₂) AOR8Status.zero

/-- A disjoint-union cascade consists of the two side cascades plus restricted cross edges. -/
structure CrossCascadeCompositionWitness (r₁ r₂ : ResidualRecord)
    (witnesses₁ witnesses₂ : List DischargeWitness) : Prop where
  edge_decomposition :
    ∀ source target status,
      (cascadeGraph (disjointUnionResidual r₁ r₂) (witnesses₁ ++ witnesses₂)).edge
        source target status →
        DisjointUnionEdgeClass r₁ r₂ witnesses₁ witnesses₂ source target status
  cross_edges_restricted :
    ∀ e : CrossCascadeEdge r₁ r₂,
      crossCascadeEdgePrimary e =
          SixBirdsMetaMath.AOR.DefectStrata.residualTypesTwelve.interface ∨
        crossCascadeEdgePrimary e =
          SixBirdsMetaMath.AOR.DefectStrata.residualTypesTwelve.local ∨
          crossCascadeEdgePrimary e =
            SixBirdsMetaMath.AOR.DefectStrata.residualTypesTwelve.global ∨
            crossCascadeEdgePrimary e =
              SixBirdsMetaMath.AOR.DefectStrata.residualTypesTwelve.sym

/--
`thm:aor:cross-cascade-composition`.

The cascade of a disjoint union is represented by the two side cascades plus
cross edges generated only by interface, local, global, and symmetry atoms.
-/
theorem crossCascadeComposition (r₁ r₂ : ResidualRecord)
    (witnesses₁ witnesses₂ : List DischargeWitness) :
    CrossCascadeCompositionWitness r₁ r₂ witnesses₁ witnesses₂ where
  edge_decomposition := by
    intro source target status h
    cases h
    case atomToWitness w hw =>
        cases (List.mem_append.mp hw) with
        | inl hleft =>
            exact DisjointUnionEdgeClass.leftAtomToWitness w hleft
        | inr hright =>
            exact DisjointUnionEdgeClass.rightAtomToWitness w hright
    case witnessToAtom w t hw hcost =>
        cases (List.mem_append.mp hw) with
        | inl hleft =>
            exact DisjointUnionEdgeClass.leftWitnessToAtom w t status hleft hcost
        | inr hright =>
            exact DisjointUnionEdgeClass.rightWitnessToAtom w t status hright hcost
  cross_edges_restricted := by
    intro e
    cases e
    · exact Or.inl rfl
    · exact Or.inr (Or.inl rfl)
    · exact Or.inr (Or.inr (Or.inl rfl))
    · exact Or.inr (Or.inr (Or.inr rfl))

/-- Finite cost-table descent from a residual/status pair to zero status. -/
inductive reachesZero : residualTypesTwelve × AOR8Status → Prop where
  | base (t : residualTypesTwelve) : reachesZero (t, AOR8Status.zero)
  | step (t : residualTypesTwelve) (s : AOR8Status)
      (t' : residualTypesTwelve) (s' : AOR8Status) :
      List.Mem (t', s') (costTable t s) →
      reachesZero (t', s') →
      reachesZero (t, s)

/-- A residual/status pair reaches zero by finitely many cost-table moves. -/
def reachableFromZero (t : residualTypesTwelve) (s : AOR8Status) : Prop :=
  reachesZero (t, s)

/-- Zero status is zero-reachable for every residual type. -/
theorem reachableFromZero_zero (t : residualTypesTwelve) :
    reachableFromZero t AOR8Status.zero :=
  reachesZero.base t

/-- The default budgeted row reaches zero through the self-zero obligation. -/
theorem reachableFromZero_budgeted (t : residualTypesTwelve) :
    reachableFromZero t AOR8Status.budgeted := by
  cases t
  · exact reachesZero.step _ AOR8Status.budgeted _ AOR8Status.zero
      (List.Mem.head _) (reachesZero.base _)
  · exact reachesZero.step _ AOR8Status.budgeted _ AOR8Status.zero
      (List.Mem.head _) (reachesZero.base _)
  · exact reachesZero.step _ AOR8Status.budgeted _ AOR8Status.zero
      (List.Mem.head _) (reachesZero.base _)
  · exact reachesZero.step _ AOR8Status.budgeted _ AOR8Status.zero
      (List.Mem.head _) (reachesZero.base _)
  · exact reachesZero.step _ AOR8Status.budgeted _ AOR8Status.zero
      (List.Mem.head _) (reachesZero.base _)
  · exact reachesZero.step _ AOR8Status.budgeted _ AOR8Status.zero
      (List.Mem.head _) (reachesZero.base _)
  · exact reachesZero.step _ AOR8Status.budgeted _ AOR8Status.zero
      (List.Mem.head _) (reachesZero.base _)
  · exact reachesZero.step _ AOR8Status.budgeted _ AOR8Status.zero
      (List.Mem.head _) (reachesZero.base _)
  · exact reachesZero.step _ AOR8Status.budgeted _ AOR8Status.zero
      (List.Mem.head _) (reachesZero.base _)
  · exact reachesZero.step _ AOR8Status.budgeted _ AOR8Status.zero
      (List.Mem.head _) (reachesZero.base _)
  · exact reachesZero.step _ AOR8Status.budgeted _ AOR8Status.zero
      (List.Mem.head _) (reachesZero.base _)
  · exact reachesZero.step _ AOR8Status.budgeted _ AOR8Status.zero
      (List.Mem.head _) (reachesZero.base _)
  · exact reachesZero.step _ AOR8Status.budgeted _ AOR8Status.zero
      (List.Mem.head _) (reachesZero.base _)

/-- Iterated downstream records from an initial residual record. -/
def omegaDown : Nat → ResidualRecord → ResidualRecord
  | 0, r => r
  | n + 1, r =>
      match r.secondary with
      | [] => r
      | _ :: rest =>
          omegaDown n
            { primary := r.primary, secondary := rest, refinementDepth := 0 }

/-- The empty residual record used as terminal cascade normal form. -/
def emptyResidualRecord (primary : residualTypesTwelve) : ResidualRecord where
  primary := primary
  secondary := []
  refinementDepth := 0

/-- Eventual emptiness of the omega-iteration of `Down`. -/
def eventuallyEmptyByDown (r : ResidualRecord) : Prop :=
  ∃ n, omegaDown n r = emptyResidualRecord r.primary

/-- The residual record represented by a residual-stratum atom. -/
def residualRecordOfAtom {mathfrakS : scopeRecord.{u}}
    {C : preSBCarrier mathfrakS}
    (atom : SixBirdsMetaMath.AOR.DefectStrata.sigmaResidual C) : ResidualRecord where
  primary := residualPrimaryType atom
  secondary := forcedSecondaryTypes (residualPrimaryType atom)
  refinementDepth := 0

/-- `omegaDown` removes one secondary obligation per step. -/
theorem omegaDown_clearsSecondary (primary : residualTypesTwelve) :
    ∀ secondary : List residualTypesTwelve,
      omegaDown secondary.length
        { primary := primary, secondary := secondary, refinementDepth := 0 } =
          emptyResidualRecord primary
  | [] => rfl
  | _ :: rest => by
      simpa [omegaDown] using omegaDown_clearsSecondary primary rest

/-- After one pass through the secondary list, no secondary obligations remain. -/
theorem omegaDown_clearsSecondaryLength (r : ResidualRecord) :
    (omegaDown r.secondary.length r).secondary = [] := by
  cases r with
  | mk primary secondary refinementDepth =>
      induction secondary generalizing refinementDepth with
      | nil => rfl
      | cons head rest ih =>
          simpa [omegaDown] using ih 0

/-- An extra `omegaDown` step preserves an already empty secondary list. -/
theorem omegaDown_clearsSecondaryLength_succ (r : ResidualRecord) :
    (omegaDown (r.secondary.length + 1) r).secondary = [] := by
  cases r with
  | mk primary secondary refinementDepth =>
      induction secondary generalizing refinementDepth with
      | nil => rfl
      | cons head rest ih =>
          simpa [omegaDown] using ih 0

/-- Every residual atom reaches the empty record by walking its forced secondaries. -/
theorem residualRecordOfAtom_eventuallyEmpty {mathfrakS : scopeRecord.{u}}
    {C : preSBCarrier mathfrakS}
    (atom : SixBirdsMetaMath.AOR.DefectStrata.sigmaResidual C) :
    eventuallyEmptyByDown (residualRecordOfAtom atom) :=
  ⟨(forcedSecondaryTypes (residualPrimaryType atom)).length, by
    simpa [eventuallyEmptyByDown, residualRecordOfAtom] using
      omegaDown_clearsSecondary (residualPrimaryType atom)
        (forcedSecondaryTypes (residualPrimaryType atom))⟩

/-- A fixed-scope AOR carrier paired with its declared residual-status assignment. -/
structure AORCarrierWithDischarge (mathfrakS : scopeRecord.{u}) where
  toCarrier : aorSubcategory mathfrakS
  dischargeAssignment :
    SixBirdsMetaMath.AOR.DefectStrata.sigmaResidual (aorInclusionObj toCarrier) → AOR8Status
  /-- Quantitative cost of a residual at each refinement stage. This is
  separate from its finite cascade status. -/
  limitCost :
    SixBirdsMetaMath.AOR.DefectStrata.sigmaResidual (aorInclusionObj toCarrier) →
      Nat → Nat

/-- Cost-table and structural downstream closure under an assigned status. -/
def eventuallyEmptyUnder (r : ResidualRecord) (status : AOR8Status) : Prop :=
  reachesZero (r.primary, status) ∧ eventuallyEmptyByDown r

/-- Characterisation predicate for cascade-stable AOR carriers. -/
def cascadeStablePredicate {mathfrakS : scopeRecord.{u}}
    (C : AORCarrierWithDischarge mathfrakS) : Prop :=
  ∀ atom : SixBirdsMetaMath.AOR.DefectStrata.sigmaResidual (aorInclusionObj C.toCarrier),
    eventuallyEmptyUnder (residualRecordOfAtom atom) (C.dischargeAssignment atom)

/--
`def:aor:cascade-stable-aor`.

An AOR carrier is cascade-stable when every residual atom has a base AOR-8
status reachable from `zero` and its downstream iteration eventually reaches
the empty residual record.
-/
def cascadeStableAOR {mathfrakS : scopeRecord.{u}}
    (C : AORCarrierWithDischarge mathfrakS) : Prop :=
  ∀ atom : SixBirdsMetaMath.AOR.DefectStrata.sigmaResidual (aorInclusionObj C.toCarrier),
    reachesZero (residualPrimaryType atom, C.dischargeAssignment atom) ∧
      eventuallyEmptyByDown (residualRecordOfAtom atom)

/--
`thm:aor:cascade-stable-characterisation`.

Cascade stability is equivalent to the finite cost-table reachability of every
residual atom and eventual emptiness of the omega-iteration of `Down`.
-/
theorem cascadeStableCharacterisation {mathfrakS : scopeRecord.{u}}
    (C : AORCarrierWithDischarge mathfrakS) :
    cascadeStableAOR C ↔ cascadeStablePredicate C := by
  constructor
  · intro h
    intro atom
    exact h atom
  · intro h
    intro atom
    exact h atom

end SixBirdsMetaMath.AOR.Cascades
