import SixBirdsMetaMath.FoundationsIV.Access.Adequacy

/-!
F12 No-Free-Distinction.

At fixed access, a proposed current distinction is lawful only when it already
factors through the current quotient. If it splits a current fiber, the split is
not free: it must be paid for by a strict access extension, instrument change,
memory retyping, bridge, residual budget, scope restriction, or blocked status.
-/

namespace SixBirdsMetaMath.FoundationsIV.Access.NoFreeDistinction

open SixBirdsMetaMath.FoundationsIV.Transport.DescentRepair
open SixBirdsMetaMath.FoundationsIV.Stability.SufficiencyClosure
open SixBirdsMetaMath.FoundationsIV.Access.Quotientality
open SixBirdsMetaMath.FoundationsIV.Access.Adequacy

/-- Same current object, different proposed distinction. -/
def DistinctionSplitPair {H Q D : Type} (q : H → Q) (distinction : H → D) :
    (H × H) → Prop :=
  SufficiencySplitPair q distinction

/-- No fixed-access distinction split is present. -/
def DistinctionObstructionEmpty {H Q D : Type} (q : H → Q)
    (distinction : H → D) : Prop :=
  ObstructionEmpty (DistinctionSplitPair q distinction)

/-- The proposed distinction is definable from the current access quotient. -/
def DefinableFromAccess {H Q D : Type} (q : H → Q)
    (distinction : H → D) : Prop :=
  FactorsThroughQ q distinction

/-- A proposed distinction genuinely splits at least one current fiber. -/
def HasDistinctionSplit {H Q D : Type} (q : H → Q)
    (distinction : H → D) : Prop :=
  ∃ x y : H, q x = q y ∧ distinction x ≠ distinction y

/-- The canonical financed refinement generated by a distinction. -/
def financedRefinement {H Q D : Type} (q : H → Q) (distinction : H → D) :
    H → Q × D :=
  fun h => (q h, distinction h)

/-- A package retains the old access quotient when the old quotient factors
through it. -/
def RetainsAccess {H Q S : Type} (q : H → Q) (package : H → S) : Prop :=
  FactorsThroughQ package q

/-- A package carries the proposed distinction when the distinction factors
through it. -/
def CarriesDistinction {H S D : Type} (package : H → S)
    (distinction : H → D) : Prop :=
  FactorsThroughQ package distinction

/-- A retentive package is strict when it splits an old access fiber. -/
def StrictAccessExtension {H Q S : Type} (q : H → Q) (package : H → S) : Prop :=
  RetainsAccess q package ∧
    ∃ x y : H, q x = q y ∧ package x ≠ package y

/-- The paid/statused outcomes for a nondefinable distinction. -/
def DistinctionCosted (strictAccessExtension instrumentExtension memoryRetyping
    bridgedDistinction budgetedDistinction scopedDistinction blockedOverread :
    Prop) : Prop :=
  strictAccessExtension ∨ instrumentExtension ∨ memoryRetyping ∨
    LawfulBeyondAccess False bridgedDistinction budgetedDistinction ∨
      scopedDistinction ∨ blockedOverread

/-- A new split has been either absent or paid/statused. -/
def NoFreeDistinctionOutcome (hasSplit costed : Prop) : Prop :=
  ¬ hasSplit ∨ costed

/-- The forbidden case: a real split with no installed cost or status. -/
def UnpaidNewDistinction (hasSplit costed : Prop) : Prop :=
  hasSplit ∧ ¬ costed

/-- F12 status vocabulary. -/
inductive NoFreeDistinctionStatus where
  | inheritedCurrentDistinction
  | strictAccessExtension
  | instrumentExtension
  | retypedMemoryOrPredictive
  | bridgedDistinction
  | budgetedDistinction
  | scopedDistinction
  | failedNoFreeDistinction
deriving DecidableEq

/-- Meaning of each no-free-distinction status. -/
def NoFreeDistinctionStatusHolds (inherited strictAccess instrument memory
    bridged budgeted scopedDist blocked : Prop) :
    NoFreeDistinctionStatus → Prop
  | NoFreeDistinctionStatus.inheritedCurrentDistinction => inherited
  | NoFreeDistinctionStatus.strictAccessExtension => strictAccess
  | NoFreeDistinctionStatus.instrumentExtension => instrument
  | NoFreeDistinctionStatus.retypedMemoryOrPredictive => memory
  | NoFreeDistinctionStatus.bridgedDistinction => bridged
  | NoFreeDistinctionStatus.budgetedDistinction => budgeted
  | NoFreeDistinctionStatus.scopedDistinction => scopedDist
  | NoFreeDistinctionStatus.failedNoFreeDistinction => blocked

/-- The split-pair obstruction is empty exactly when no explicit split exists. -/
theorem has_distinction_split_iff_not_empty {H Q D : Type} (q : H → Q)
    (distinction : H → D) :
    HasDistinctionSplit q distinction ↔
      ¬ DistinctionObstructionEmpty q distinction := by
  constructor
  · intro hsplit hempty
    rcases hsplit with ⟨x, y, hq, hdist⟩
    exact hempty (x, y) ⟨hq, hdist⟩
  · intro hnotEmpty
    exact Classical.byContradiction (fun hnoSplit => by
      apply hnotEmpty
      intro pair hpair
      rcases pair with ⟨x, y⟩
      exact hnoSplit ⟨x, y, hpair.1, hpair.2⟩)

/-- Fixed-access definability is exactly absence of the distinction split-pair
obstruction. -/
theorem distinction_definable_iff_no_split {H Q D : Type} (q : H → Q)
    (distinction : H → D) (hq : Function.Surjective q) :
    DefinableFromAccess q distinction ↔
      DistinctionObstructionEmpty q distinction := by
  constructor
  · intro hfactors
    have hclosed : PackageClosed q distinction :=
      (sufficiency_closure q distinction hq).1.2 hfactors
    exact (sufficiency_closure q distinction hq).2.1.1 hclosed
  · intro hempty
    have hclosed : PackageClosed q distinction :=
      (sufficiency_closure q distinction hq).2.1.2 hempty
    exact (sufficiency_closure q distinction hq).1.1 hclosed

/-- The financed refinement retains the old access quotient. -/
theorem financed_refinement_retains_access {H Q D : Type} (q : H → Q)
    (distinction : H → D) :
    RetainsAccess q (financedRefinement q distinction) := by
  refine ⟨Prod.fst, ?_⟩
  funext h
  rfl

/-- The financed refinement carries the proposed distinction. -/
theorem financed_refinement_carries_distinction {H Q D : Type} (q : H → Q)
    (distinction : H → D) :
    CarriesDistinction (financedRefinement q distinction) distinction := by
  refine ⟨Prod.snd, ?_⟩
  funext h
  rfl

/-- If the proposed distinction splits an old fiber, the financed refinement is
a strict retentive access extension. -/
theorem financed_refinement_strict_of_split {H Q D : Type} (q : H → Q)
    (distinction : H → D) :
    HasDistinctionSplit q distinction →
      StrictAccessExtension q (financedRefinement q distinction) := by
  intro hsplit
  rcases hsplit with ⟨x, y, hqxy, hdist⟩
  refine ⟨financed_refinement_retains_access q distinction, ?_⟩
  refine ⟨x, y, hqxy, ?_⟩
  intro hrefine
  exact hdist (congrArg Prod.snd hrefine)

/-- The financed refinement factors through every package carrying both
the old access quotient and the new distinction. -/
theorem financed_refinement_minimal {H Q D S : Type} (q : H → Q)
    (distinction : H → D) (package : H → S)
    (hretains : RetainsAccess q package)
    (hcarries : CarriesDistinction package distinction) :
    FactorsThroughQ package (financedRefinement q distinction) := by
  rcases hretains with ⟨oldReadout, hold⟩
  rcases hcarries with ⟨distReadout, hdist⟩
  refine ⟨fun s => (oldReadout s, distReadout s), ?_⟩
  funext h
  exact Prod.ext (congrFun hold h) (congrFun hdist h)

/-- A paid/statused outcome is exactly absence of an unpaid new distinction. -/
theorem no_free_outcome_iff_no_unpaid (hasSplit costed : Prop) :
    NoFreeDistinctionOutcome hasSplit costed ↔
      ¬ UnpaidNewDistinction hasSplit costed := by
  classical
  constructor
  · intro houtcome hunpaid
    cases houtcome with
    | inl hnoSplit =>
        exact hnoSplit hunpaid.1
    | inr hcosted =>
        exact hunpaid.2 hcosted
  · intro hnotUnpaid
    by_cases hsplit : hasSplit
    · by_cases hcosted : costed
      · exact Or.inr hcosted
      · exact False.elim (hnotUnpaid ⟨hsplit, hcosted⟩)
    · exact Or.inl hsplit

/--
No-Free-Distinction Normal Form. A proposed distinction is current-visible at
fixed access iff its split-pair obstruction is empty, equivalently iff it
factors through the access quotient. If a current accepted distinction is
claimed at the unchanged quotient, it has no split. If there is a split, the
canonical paid refinement `(q, d)` retains old access, carries `d`, and is
strict; otherwise the split must receive a bridge, budget, memory/instrument
retyping, scope restriction, or blocked status.
-/
theorem no_free_distinction {H Q D : Type} (q : H → Q) (distinction : H → D)
    (hq : Function.Surjective q)
    (acceptedCurrent : Prop)
    (accepted_visible : acceptedCurrent → CurrentVisible q distinction)
    (strictAccessExtension instrumentExtension memoryRetyping bridgedDistinction
      budgetedDistinction scopedDistinction blockedOverread : Prop) :
    (DefinableFromAccess q distinction ↔
        DistinctionObstructionEmpty q distinction) ∧
      (acceptedCurrent →
        DistinctionObstructionEmpty q distinction ∧
          DefinableFromAccess q distinction) ∧
        (HasDistinctionSplit q distinction → ¬ acceptedCurrent) ∧
          RetainsAccess q (financedRefinement q distinction) ∧
            CarriesDistinction (financedRefinement q distinction) distinction ∧
              (HasDistinctionSplit q distinction →
                StrictAccessExtension q (financedRefinement q distinction)) ∧
                (NoFreeDistinctionOutcome (HasDistinctionSplit q distinction)
                    (DistinctionCosted strictAccessExtension instrumentExtension
                      memoryRetyping bridgedDistinction budgetedDistinction
                      scopedDistinction blockedOverread) ↔
                  ¬ UnpaidNewDistinction (HasDistinctionSplit q distinction)
                    (DistinctionCosted strictAccessExtension instrumentExtension
                      memoryRetyping bridgedDistinction budgetedDistinction
                      scopedDistinction blockedOverread)) := by
  have hdefIff := distinction_definable_iff_no_split q distinction hq
  refine ⟨hdefIff, ?_⟩
  constructor
  · intro haccepted
    have hclosed : PackageClosed q distinction := accepted_visible haccepted
    have hempty : DistinctionObstructionEmpty q distinction :=
      (sufficiency_closure q distinction hq).2.1.1 hclosed
    exact ⟨hempty, hdefIff.2 hempty⟩
  · constructor
    · intro hsplit haccepted
      have hempty : DistinctionObstructionEmpty q distinction :=
        (sufficiency_closure q distinction hq).2.1.1
          (accepted_visible haccepted)
      rcases hsplit with ⟨x, y, hqxy, hdist⟩
      exact hempty (x, y) ⟨hqxy, hdist⟩
    · exact ⟨financed_refinement_retains_access q distinction,
        financed_refinement_carries_distinction q distinction,
        financed_refinement_strict_of_split q distinction,
        no_free_outcome_iff_no_unpaid
          (HasDistinctionSplit q distinction)
          (DistinctionCosted strictAccessExtension instrumentExtension
            memoryRetyping bridgedDistinction budgetedDistinction
            scopedDistinction blockedOverread)⟩

/-- Current visibility is exactly absence of the distinction obstruction. -/
theorem current_visible_iff_distinction_obstruction_empty
    {H Q D : Type} (q : H → Q) (distinction : H → D)
    (hq : Function.Surjective q) :
    CurrentVisible q distinction ↔ DistinctionObstructionEmpty q distinction :=
  (sufficiency_closure q distinction hq).2.1

/-- F12 with visibility, the paid repair, and its universal factorization. -/
theorem no_free_distinction_paper {H Q D : Type}
    (q : H → Q) (distinction : H → D)
    (hq : Function.Surjective q)
    (acceptedCurrent : Prop)
    (accepted_visible : acceptedCurrent → CurrentVisible q distinction)
    (strictAccessExtension instrumentExtension memoryRetyping bridgedDistinction
      budgetedDistinction scopedDistinction blockedOverread : Prop) :
    (CurrentVisible q distinction ↔ DistinctionObstructionEmpty q distinction) ∧
    (DefinableFromAccess q distinction ↔
      DistinctionObstructionEmpty q distinction) ∧
    (acceptedCurrent →
      DistinctionObstructionEmpty q distinction ∧
        DefinableFromAccess q distinction) ∧
    (HasDistinctionSplit q distinction → ¬ acceptedCurrent) ∧
    RetainsAccess q (financedRefinement q distinction) ∧
    CarriesDistinction (financedRefinement q distinction) distinction ∧
    (HasDistinctionSplit q distinction →
      StrictAccessExtension q (financedRefinement q distinction)) ∧
    (∀ {S : Type} (package : H → S),
      RetainsAccess q package → CarriesDistinction package distinction →
        FactorsThroughQ package (financedRefinement q distinction)) ∧
    (NoFreeDistinctionOutcome (HasDistinctionSplit q distinction)
      (DistinctionCosted strictAccessExtension instrumentExtension
        memoryRetyping bridgedDistinction budgetedDistinction
        scopedDistinction blockedOverread) ↔
      ¬ UnpaidNewDistinction (HasDistinctionSplit q distinction)
        (DistinctionCosted strictAccessExtension instrumentExtension
          memoryRetyping bridgedDistinction budgetedDistinction
          scopedDistinction blockedOverread)) := by
  rcases no_free_distinction q distinction hq acceptedCurrent accepted_visible
      strictAccessExtension instrumentExtension memoryRetyping
      bridgedDistinction budgetedDistinction scopedDistinction blockedOverread with
    ⟨hdef, haccept, hsplit, hretains, hcarries, hstrict, hstatus⟩
  exact ⟨current_visible_iff_distinction_obstruction_empty q distinction hq,
    hdef, haccept, hsplit, hretains, hcarries, hstrict,
    fun package hret hcarr =>
      financed_refinement_minimal q distinction package hret hcarr,
    hstatus⟩

end SixBirdsMetaMath.FoundationsIV.Access.NoFreeDistinction
