import SixBirdsMetaMath.FoundationsIV.Transport.DescentRepair

/-!
F51 Unification as Common Refinement.

Unification is modeled as a formed parent package whose projections recover two
law packages as quotient shadows. The normal form separates weak common-parent
unification from substantive unification: exact unification requires object
projection, law/status carriage, transport preservation, role preservation, and
cross-residual closure; substantive unification additionally needs non-product
structure or compression.
-/

namespace SixBirdsMetaMath.FoundationsIV.SelfReferenceLimits.Unification

open SixBirdsMetaMath.FoundationsIV.Transport.DescentRepair

/-- Object projection from a candidate parent package to an old package:
the old object quotient descends through the parent quotient. -/
def ObjectProjectionDescends {HU QU HOld QOld : Type} (qU : HU → QU)
    (interpret : HU → HOld) (qOld : HOld → QOld) : Prop :=
  Descends qU interpret qOld

/-- Object-projection obstruction: parent-identical states have different old
object shadows. -/
def ObjectProjectionObstruction {HU QU HOld QOld : Type} (qU : HU → QU)
    (interpret : HU → HOld) (qOld : HOld → QOld) : (HU × HU) → Prop :=
  splitPairObstruction qU interpret qOld

/-- No object-projection obstruction is present. -/
def ObjectProjectionObstructionEmpty {HU QU HOld QOld : Type} (qU : HU → QU)
    (interpret : HU → HOld) (qOld : HOld → QOld) : Prop :=
  ObstructionEmpty (ObjectProjectionObstruction qU interpret qOld)

/-- Object projection with a specified quotient map `π : Q_U -> Q_old`. -/
def ObjectProjectionWithMap {HU QU HOld QOld : Type} (qU : HU → QU)
    (interpret : HU → HOld) (qOld : HOld → QOld) (π : QU → QOld) : Prop :=
  π ∘ qU = qOld ∘ interpret

/-- A common refinement carries both old object quotients as shadows. -/
def CommonRefinement {HU QU HA QA HB QB : Type} (qU : HU → QU)
    (interpretA : HU → HA) (qA : HA → QA)
    (interpretB : HU → HB) (qB : HB → QB) : Prop :=
  ObjectProjectionDescends qU interpretA qA ∧
    ObjectProjectionDescends qU interpretB qB

/-- Law/status carriage: every old law or claim has a lifted unified claim
whose status agrees with the declared status map. -/
def LawStatusCarriage {OldClaim UnifiedClaim OldStatus UnifiedStatus : Type}
    (lift : OldClaim → UnifiedClaim) (oldStatus : OldClaim → OldStatus)
    (unifiedStatus : UnifiedClaim → UnifiedStatus)
    (statusMap : OldStatus → UnifiedStatus) : Prop :=
  ∀ claim, unifiedStatus (lift claim) = statusMap (oldStatus claim)

/-- Law/status obstruction: a lifted claim has the wrong status. -/
def LawStatusObstruction {OldClaim UnifiedClaim OldStatus UnifiedStatus : Type}
    (lift : OldClaim → UnifiedClaim) (oldStatus : OldClaim → OldStatus)
    (unifiedStatus : UnifiedClaim → UnifiedStatus)
    (statusMap : OldStatus → UnifiedStatus) : OldClaim → Prop :=
  fun claim => unifiedStatus (lift claim) ≠ statusMap (oldStatus claim)

/-- No law/status obstruction is present. -/
def LawStatusObstructionEmpty {OldClaim UnifiedClaim OldStatus UnifiedStatus : Type}
    (lift : OldClaim → UnifiedClaim) (oldStatus : OldClaim → OldStatus)
    (unifiedStatus : UnifiedClaim → UnifiedStatus)
    (statusMap : OldStatus → UnifiedStatus) : Prop :=
  ObstructionEmpty (LawStatusObstruction lift oldStatus unifiedStatus statusMap)

/-- Transport preservation for a route shadow: projecting after the unified
route agrees with applying the old route after projection. -/
def TransportPreserved {QU QOld : Type} (π : QU → QOld)
    (routeU : QU → QU) (routeOld : QOld → QOld) : Prop :=
  ∀ u, π (routeU u) = routeOld (π u)

/-- Transport obstruction: a route diagram fails to commute at one parent
object. -/
def TransportObstruction {QU QOld : Type} (π : QU → QOld)
    (routeU : QU → QU) (routeOld : QOld → QOld) : QU → Prop :=
  fun u => π (routeU u) ≠ routeOld (π u)

/-- No transport obstruction is present. -/
def TransportObstructionEmpty {QU QOld : Type} (π : QU → QOld)
    (routeU : QU → QU) (routeOld : QOld → QOld) : Prop :=
  ObstructionEmpty (TransportObstruction π routeU routeOld)

/-- Role preservation is kept as a declared typed gate: sources, targets,
records, residuals, laws, boundaries, and audits must keep their role map. -/
def RolePreservation (roleGate : Prop) : Prop :=
  roleGate

/-- Cross-residual closure: every residual generated by putting the two law
structures in the parent package passes its declared status gate. -/
def CrossResidualClosed {CrossResidual : Type}
    (residualPassesStatus : CrossResidual → Prop) : Prop :=
  ∀ residual, residualPassesStatus residual

/-- Cross-residual obstruction: an unstatused or failed cross residual. -/
def CrossResidualObstruction {CrossResidual : Type}
    (residualPassesStatus : CrossResidual → Prop) : CrossResidual → Prop :=
  fun residual => ¬ residualPassesStatus residual

/-- No cross-residual obstruction is present. -/
def CrossResidualObstructionEmpty {CrossResidual : Type}
    (residualPassesStatus : CrossResidual → Prop) : Prop :=
  ObstructionEmpty (CrossResidualObstruction residualPassesStatus)

/-- Exact unification is the six-gate parent-package condition. Law and
transport gates are split for the A and B shadows. -/
def ExactUnifier (parentFormed objectA objectB lawA lawB transportA transportB
    rolePreserved crossResidualsClosed : Prop) : Prop :=
  parentFormed ∧ objectA ∧ objectB ∧ lawA ∧ lawB ∧ transportA ∧ transportB ∧
    rolePreserved ∧ crossResidualsClosed

/-- Substantive unification is exact unification plus an anti-product or
compression/shared-structure witness. -/
def SubstantiveUnifier (exactUnifier antiProductOrCompression : Prop) : Prop :=
  exactUnifier ∧ antiProductOrCompression

/-- Product juxtaposition carries both packages side by side but does not by
itself establish substantive unification. -/
def ProductJuxtaposition (exactUnifier productEquivalent : Prop) : Prop :=
  exactUnifier ∧ productEquivalent

/-- Partial unification records that only declared subpackages are carried. -/
def PartialUnification (subpackageSpecified subpackageUnifies : Prop) : Prop :=
  subpackageSpecified ∧ subpackageUnifies

/-- Approximate/asymptotic unification keeps a residual budget or limit status,
so it is not exact unification. -/
def BudgetedUnification (residualBudgeted : Prop) : Prop :=
  residualBudgeted

/-- Source status vocabulary for F51 unification claims. -/
inductive UnificationStatus where
  | exactUnification
  | substantiveUnification
  | productJuxtaposition
  | commonAbstraction
  | commonCoarsening
  | partialUnification
  | targetUnification
  | dynamicUnification
  | staticUnificationOnly
  | bridgeMediatedAlignment
  | duality
  | embedding
  | reduction
  | unificationObstructed
  | objectProjectionFailure
  | roleMismatch
  | sourceReadoutMismatch
  | residualMismatch
  | anomalyObstructedUnification
  | interfaceMediatedUnification
  | hiddenUnifier
  | probabilisticUnification
  | approximateUnification
  | asymptoticUnification
  | localUnification
  | globalUnificationObstructed
  | presentationEquivalence
  | protocolUnificationArtifact
  | commonSourceUnification
  | strictUnifyingExtension
  | emergentUnification
  | continuumUnification
  | completedUnification
  | unificationBreaking
  | unificationRestoration
  | anomalyCancelledUnification
  | conservationUnification
  | nonlocalUnifier
  | topologicalUnification
  | unifierModuli
  | backgroundSelectedUnification
  | fineTunedUnification
  | unificationIrreducible
  | unificationOverread
deriving DecidableEq

/-- Meaning assignment for the F51 unification status vocabulary. -/
def UnificationStatusHolds (exact substantive product commonAbstraction
    commonCoarsening partialStatus target dynamic staticOnly bridge duality embedding reduction
    obstructed objectFailure roleMismatch sourceReadout residualMismatch anomalyObstructed
    interfaceMediated hidden probabilistic approximate asymptotic localStatus globalObstructed
    presentation protocol commonSource strictExtension emergent continuum completed breaking
    restoration anomalyCancelled conservation nonlocal topological moduli backgroundSelected
    fineTuned irreducible overread : Prop) : UnificationStatus → Prop
  | UnificationStatus.exactUnification => exact
  | UnificationStatus.substantiveUnification => substantive
  | UnificationStatus.productJuxtaposition => product
  | UnificationStatus.commonAbstraction => commonAbstraction
  | UnificationStatus.commonCoarsening => commonCoarsening
  | UnificationStatus.partialUnification => partialStatus
  | UnificationStatus.targetUnification => target
  | UnificationStatus.dynamicUnification => dynamic
  | UnificationStatus.staticUnificationOnly => staticOnly
  | UnificationStatus.bridgeMediatedAlignment => bridge
  | UnificationStatus.duality => duality
  | UnificationStatus.embedding => embedding
  | UnificationStatus.reduction => reduction
  | UnificationStatus.unificationObstructed => obstructed
  | UnificationStatus.objectProjectionFailure => objectFailure
  | UnificationStatus.roleMismatch => roleMismatch
  | UnificationStatus.sourceReadoutMismatch => sourceReadout
  | UnificationStatus.residualMismatch => residualMismatch
  | UnificationStatus.anomalyObstructedUnification => anomalyObstructed
  | UnificationStatus.interfaceMediatedUnification => interfaceMediated
  | UnificationStatus.hiddenUnifier => hidden
  | UnificationStatus.probabilisticUnification => probabilistic
  | UnificationStatus.approximateUnification => approximate
  | UnificationStatus.asymptoticUnification => asymptotic
  | UnificationStatus.localUnification => localStatus
  | UnificationStatus.globalUnificationObstructed => globalObstructed
  | UnificationStatus.presentationEquivalence => presentation
  | UnificationStatus.protocolUnificationArtifact => protocol
  | UnificationStatus.commonSourceUnification => commonSource
  | UnificationStatus.strictUnifyingExtension => strictExtension
  | UnificationStatus.emergentUnification => emergent
  | UnificationStatus.continuumUnification => continuum
  | UnificationStatus.completedUnification => completed
  | UnificationStatus.unificationBreaking => breaking
  | UnificationStatus.unificationRestoration => restoration
  | UnificationStatus.anomalyCancelledUnification => anomalyCancelled
  | UnificationStatus.conservationUnification => conservation
  | UnificationStatus.nonlocalUnifier => nonlocal
  | UnificationStatus.topologicalUnification => topological
  | UnificationStatus.unifierModuli => moduli
  | UnificationStatus.backgroundSelectedUnification => backgroundSelected
  | UnificationStatus.fineTunedUnification => fineTuned
  | UnificationStatus.unificationIrreducible => irreducible
  | UnificationStatus.unificationOverread => overread

/-- Object projection has the F2 descent/obstruction normal form. -/
theorem object_projection_iff_no_obstruction {HU QU HOld QOld : Type}
    (qU : HU → QU) (interpret : HU → HOld) (qOld : HOld → QOld)
    (hqU : Function.Surjective qU) :
    ObjectProjectionDescends qU interpret qOld ↔
      ObjectProjectionObstructionEmpty qU interpret qOld :=
  descent_repair_normal_form qU interpret qOld hqU

/-- A specified object projection map is a witness for object projection
descent. -/
theorem object_projection_with_map_descends {HU QU HOld QOld : Type}
    (qU : HU → QU) (interpret : HU → HOld) (qOld : HOld → QOld)
    (π : QU → QOld) (hπ : ObjectProjectionWithMap qU interpret qOld π) :
    ObjectProjectionDescends qU interpret qOld := by
  exact ⟨π, hπ⟩

/-- Law/status carriage is exactly absence of law/status mismatch. -/
theorem law_status_carriage_iff_no_obstruction
    {OldClaim UnifiedClaim OldStatus UnifiedStatus : Type}
    (lift : OldClaim → UnifiedClaim) (oldStatus : OldClaim → OldStatus)
    (unifiedStatus : UnifiedClaim → UnifiedStatus)
    (statusMap : OldStatus → UnifiedStatus) :
    LawStatusCarriage lift oldStatus unifiedStatus statusMap ↔
      LawStatusObstructionEmpty lift oldStatus unifiedStatus statusMap := by
  constructor
  · intro hcarry claim hobstruction
    exact hobstruction (hcarry claim)
  · intro hempty claim
    exact Classical.byContradiction (fun hneq =>
      False.elim (hempty claim hneq))

/-- Transport preservation is exactly absence of route-diagram obstruction. -/
theorem transport_preservation_iff_no_obstruction {QU QOld : Type}
    (π : QU → QOld) (routeU : QU → QU) (routeOld : QOld → QOld) :
    TransportPreserved π routeU routeOld ↔
      TransportObstructionEmpty π routeU routeOld := by
  constructor
  · intro hpreserved u hobstruction
    exact hobstruction (hpreserved u)
  · intro hempty u
    exact Classical.byContradiction (fun hneq =>
      False.elim (hempty u hneq))

/-- Cross-residual closure is exactly absence of unstatused or failed
cross-residuals. -/
theorem cross_residual_closed_iff_no_obstruction {CrossResidual : Type}
    (residualPassesStatus : CrossResidual → Prop) :
    CrossResidualClosed residualPassesStatus ↔
      CrossResidualObstructionEmpty residualPassesStatus := by
  constructor
  · intro hclosed residual hobstruction
    exact hobstruction (hclosed residual)
  · intro hempty residual
    exact Classical.byContradiction (fun hfailed =>
      False.elim (hempty residual hfailed))

/-- Exact unification is definitionally the six-gate formed-parent package
condition. -/
theorem exact_unifier_iff_gates (parentFormed objectA objectB lawA lawB
    transportA transportB rolePreserved crossResidualsClosed : Prop) :
    ExactUnifier parentFormed objectA objectB lawA lawB transportA transportB
        rolePreserved crossResidualsClosed ↔
      parentFormed ∧ objectA ∧ objectB ∧ lawA ∧ lawB ∧ transportA ∧
        transportB ∧ rolePreserved ∧ crossResidualsClosed := by
  constructor
  · intro h
    exact h
  · intro h
    exact h

/-- Substantive unification is exact unification plus an anti-product or
compression/shared-structure witness. -/
theorem substantive_unifier_iff (exactUnifier antiProductOrCompression : Prop) :
    SubstantiveUnifier exactUnifier antiProductOrCompression ↔
      exactUnifier ∧ antiProductOrCompression := by
  constructor
  · intro h
    exact h
  · intro h
    exact h

/-- Product juxtaposition is exact weak unification plus product-equivalence,
not substantive unification by itself. -/
theorem product_juxtaposition_iff (exactUnifier productEquivalent : Prop) :
    ProductJuxtaposition exactUnifier productEquivalent ↔
      exactUnifier ∧ productEquivalent := by
  constructor
  · intro h
    exact h
  · intro h
    exact h

/--
Unification as Common Refinement Normal Form. Object projections are quotient
descent records from the parent quotient; law/status carriage, transport
preservation, and cross-residual closure are exactly their obstruction-empty
conditions. Exact unification is the conjunction of parent formation, the two
object projections, both law/status carriages, both transport shadows, role
preservation, and cross-residual closure. Substantive unification adds an
anti-product/compression witness.
-/
theorem unification_as_common_refinement
    {HU QU HA QA HB QB ClaimA ClaimB ClaimU StatusA StatusB StatusU
      CrossResidual : Type}
    (qU : HU → QU) (interpretA : HU → HA) (qA : HA → QA)
    (interpretB : HU → HB) (qB : HB → QB)
    (πA : QU → QA) (routeUA : QU → QU) (routeA : QA → QA)
    (πB : QU → QB) (routeUB : QU → QU) (routeB : QB → QB)
    (liftA : ClaimA → ClaimU) (statusA : ClaimA → StatusA)
    (liftB : ClaimB → ClaimU) (statusB : ClaimB → StatusB)
    (statusU : ClaimU → StatusU) (statusMapA : StatusA → StatusU)
    (statusMapB : StatusB → StatusU)
    (residualPassesStatus : CrossResidual → Prop)
    (parentFormed rolePreserved antiProductOrCompression productEquivalent : Prop)
    (hqU : Function.Surjective qU) :
    (ObjectProjectionDescends qU interpretA qA ↔
      ObjectProjectionObstructionEmpty qU interpretA qA) ∧
      (ObjectProjectionDescends qU interpretB qB ↔
        ObjectProjectionObstructionEmpty qU interpretB qB) ∧
        (LawStatusCarriage liftA statusA statusU statusMapA ↔
          LawStatusObstructionEmpty liftA statusA statusU statusMapA) ∧
          (LawStatusCarriage liftB statusB statusU statusMapB ↔
            LawStatusObstructionEmpty liftB statusB statusU statusMapB) ∧
            (TransportPreserved πA routeUA routeA ↔
              TransportObstructionEmpty πA routeUA routeA) ∧
              (TransportPreserved πB routeUB routeB ↔
                TransportObstructionEmpty πB routeUB routeB) ∧
                (CrossResidualClosed residualPassesStatus ↔
                  CrossResidualObstructionEmpty residualPassesStatus) ∧
                  (ExactUnifier parentFormed
                      (ObjectProjectionDescends qU interpretA qA)
                      (ObjectProjectionDescends qU interpretB qB)
                      (LawStatusCarriage liftA statusA statusU statusMapA)
                      (LawStatusCarriage liftB statusB statusU statusMapB)
                      (TransportPreserved πA routeUA routeA)
                      (TransportPreserved πB routeUB routeB)
                      (RolePreservation rolePreserved)
                      (CrossResidualClosed residualPassesStatus) ↔
                    parentFormed ∧
                      ObjectProjectionDescends qU interpretA qA ∧
                        ObjectProjectionDescends qU interpretB qB ∧
                          LawStatusCarriage liftA statusA statusU statusMapA ∧
                            LawStatusCarriage liftB statusB statusU statusMapB ∧
                              TransportPreserved πA routeUA routeA ∧
                                TransportPreserved πB routeUB routeB ∧
                                  RolePreservation rolePreserved ∧
                                    CrossResidualClosed residualPassesStatus) ∧
                    (SubstantiveUnifier
                        (ExactUnifier parentFormed
                          (ObjectProjectionDescends qU interpretA qA)
                          (ObjectProjectionDescends qU interpretB qB)
                          (LawStatusCarriage liftA statusA statusU statusMapA)
                          (LawStatusCarriage liftB statusB statusU statusMapB)
                          (TransportPreserved πA routeUA routeA)
                          (TransportPreserved πB routeUB routeB)
                          (RolePreservation rolePreserved)
                          (CrossResidualClosed residualPassesStatus))
                        antiProductOrCompression ↔
                      ExactUnifier parentFormed
                        (ObjectProjectionDescends qU interpretA qA)
                        (ObjectProjectionDescends qU interpretB qB)
                        (LawStatusCarriage liftA statusA statusU statusMapA)
                        (LawStatusCarriage liftB statusB statusU statusMapB)
                        (TransportPreserved πA routeUA routeA)
                        (TransportPreserved πB routeUB routeB)
                        (RolePreservation rolePreserved)
                        (CrossResidualClosed residualPassesStatus) ∧
                        antiProductOrCompression) ∧
                      (ProductJuxtaposition
                          (ExactUnifier parentFormed
                            (ObjectProjectionDescends qU interpretA qA)
                            (ObjectProjectionDescends qU interpretB qB)
                            (LawStatusCarriage liftA statusA statusU statusMapA)
                            (LawStatusCarriage liftB statusB statusU statusMapB)
                            (TransportPreserved πA routeUA routeA)
                            (TransportPreserved πB routeUB routeB)
                            (RolePreservation rolePreserved)
                            (CrossResidualClosed residualPassesStatus))
                          productEquivalent ↔
                        ExactUnifier parentFormed
                          (ObjectProjectionDescends qU interpretA qA)
                          (ObjectProjectionDescends qU interpretB qB)
                          (LawStatusCarriage liftA statusA statusU statusMapA)
                          (LawStatusCarriage liftB statusB statusU statusMapB)
                          (TransportPreserved πA routeUA routeA)
                          (TransportPreserved πB routeUB routeB)
                          (RolePreservation rolePreserved)
                          (CrossResidualClosed residualPassesStatus) ∧
                          productEquivalent) := by
  refine ⟨object_projection_iff_no_obstruction qU interpretA qA hqU, ?_⟩
  refine ⟨object_projection_iff_no_obstruction qU interpretB qB hqU, ?_⟩
  refine ⟨law_status_carriage_iff_no_obstruction liftA statusA statusU statusMapA, ?_⟩
  refine ⟨law_status_carriage_iff_no_obstruction liftB statusB statusU statusMapB, ?_⟩
  refine ⟨transport_preservation_iff_no_obstruction πA routeUA routeA, ?_⟩
  refine ⟨transport_preservation_iff_no_obstruction πB routeUB routeB, ?_⟩
  refine ⟨cross_residual_closed_iff_no_obstruction residualPassesStatus, ?_⟩
  refine ⟨exact_unifier_iff_gates _ _ _ _ _ _ _ _ _, ?_⟩
  refine ⟨substantive_unifier_iff _ _, ?_⟩
  exact product_juxtaposition_iff _ _

/-- Repaired F51, retaining the specified projection maps and every displayed
equation. Parent formation, role preservation, and cross-residual status are
the additional conjuncts in the paper's exact-unification criterion. -/
theorem unification_as_common_refinement_paper
    {HU QU HA QA HB QB ClaimA ClaimB ClaimU StatusA StatusB StatusU
      CrossResidual : Type}
    (qU : HU → QU) (interpretA : HU → HA) (qA : HA → QA)
    (interpretB : HU → HB) (qB : HB → QB)
    (πA : QU → QA) (routeUA : QU → QU) (routeA : QA → QA)
    (πB : QU → QB) (routeUB : QU → QU) (routeB : QB → QB)
    (liftA : ClaimA → ClaimU) (statusA : ClaimA → StatusA)
    (liftB : ClaimB → ClaimU) (statusB : ClaimB → StatusB)
    (statusU : ClaimU → StatusU) (statusMapA : StatusA → StatusU)
    (statusMapB : StatusB → StatusU)
    (residualPassesStatus : CrossResidual → Prop)
    (parentFormed rolePreserved : Prop) :
    ExactUnifier parentFormed
        (ObjectProjectionWithMap qU interpretA qA πA)
        (ObjectProjectionWithMap qU interpretB qB πB)
        (LawStatusCarriage liftA statusA statusU statusMapA)
        (LawStatusCarriage liftB statusB statusU statusMapB)
        (TransportPreserved πA routeUA routeA)
        (TransportPreserved πB routeUB routeB)
        (RolePreservation rolePreserved)
        (CrossResidualClosed residualPassesStatus) ↔
      parentFormed ∧
        πA ∘ qU = qA ∘ interpretA ∧
        πB ∘ qU = qB ∘ interpretB ∧
        (∀ u, πA (routeUA u) = routeA (πA u)) ∧
        (∀ u, πB (routeUB u) = routeB (πB u)) ∧
        (∀ k, statusU (liftA k) = statusMapA (statusA k)) ∧
        (∀ k, statusU (liftB k) = statusMapB (statusB k)) ∧
        rolePreserved ∧ (∀ residual, residualPassesStatus residual) := by
  dsimp [ExactUnifier, ObjectProjectionWithMap, LawStatusCarriage,
    TransportPreserved, RolePreservation, CrossResidualClosed]
  constructor
  · intro h
    rcases h with ⟨a, b, c, d, e, f, g, r, s⟩
    exact ⟨a, b, c, f, g, d, e, r, s⟩
  · intro h
    rcases h with ⟨a, b, c, f, g, d, e, r, s⟩
    exact ⟨a, b, c, d, e, f, g, r, s⟩

/-- The common-refinement square follows from the two object-projection
fields of an exact unifier. -/
theorem common_refinement_square_of_exact_unifier
    {HU QU HA QA HB QB : Type}
    (qU : HU → QU) (interpretA : HU → HA) (qA : HA → QA)
    (interpretB : HU → HB) (qB : HB → QB)
    (πA : QU → QA) (πB : QU → QB)
    (parentFormed lawA lawB transportA transportB rolePreserved
      crossResidualsClosed : Prop)
    (h : ExactUnifier parentFormed
      (ObjectProjectionWithMap qU interpretA qA πA)
      (ObjectProjectionWithMap qU interpretB qB πB)
      lawA lawB transportA transportB rolePreserved crossResidualsClosed) :
    (fun z : QU => (πA z, πB z)) ∘ qU =
      (fun p : HA × HB => (qA p.1, qB p.2)) ∘
        (fun x : HU => (interpretA x, interpretB x)) := by
  have hA : πA ∘ qU = qA ∘ interpretA := h.2.1
  have hB : πB ∘ qU = qB ∘ interpretB := h.2.2.1
  funext x
  exact Prod.ext (congrFun hA x) (congrFun hB x)

/-- F51 including the common-refinement square forced by an exact unifier. -/
theorem unification_as_common_refinement_paper_with_square
    {HU QU HA QA HB QB ClaimA ClaimB ClaimU StatusA StatusB StatusU
      CrossResidual : Type}
    (qU : HU → QU) (interpretA : HU → HA) (qA : HA → QA)
    (interpretB : HU → HB) (qB : HB → QB)
    (πA : QU → QA) (routeUA : QU → QU) (routeA : QA → QA)
    (πB : QU → QB) (routeUB : QU → QU) (routeB : QB → QB)
    (liftA : ClaimA → ClaimU) (statusA : ClaimA → StatusA)
    (liftB : ClaimB → ClaimU) (statusB : ClaimB → StatusB)
    (statusU : ClaimU → StatusU) (statusMapA : StatusA → StatusU)
    (statusMapB : StatusB → StatusU)
    (residualPassesStatus : CrossResidual → Prop)
    (parentFormed rolePreserved : Prop) :
    (ExactUnifier parentFormed
        (ObjectProjectionWithMap qU interpretA qA πA)
        (ObjectProjectionWithMap qU interpretB qB πB)
        (LawStatusCarriage liftA statusA statusU statusMapA)
        (LawStatusCarriage liftB statusB statusU statusMapB)
        (TransportPreserved πA routeUA routeA)
        (TransportPreserved πB routeUB routeB)
        (RolePreservation rolePreserved)
        (CrossResidualClosed residualPassesStatus) ↔
      parentFormed ∧
        πA ∘ qU = qA ∘ interpretA ∧
        πB ∘ qU = qB ∘ interpretB ∧
        (∀ u, πA (routeUA u) = routeA (πA u)) ∧
        (∀ u, πB (routeUB u) = routeB (πB u)) ∧
        (∀ k, statusU (liftA k) = statusMapA (statusA k)) ∧
        (∀ k, statusU (liftB k) = statusMapB (statusB k)) ∧
        rolePreserved ∧ (∀ residual, residualPassesStatus residual)) ∧
    (ExactUnifier parentFormed
        (ObjectProjectionWithMap qU interpretA qA πA)
        (ObjectProjectionWithMap qU interpretB qB πB)
        (LawStatusCarriage liftA statusA statusU statusMapA)
        (LawStatusCarriage liftB statusB statusU statusMapB)
        (TransportPreserved πA routeUA routeA)
        (TransportPreserved πB routeUB routeB)
        (RolePreservation rolePreserved)
        (CrossResidualClosed residualPassesStatus) →
      (fun z : QU => (πA z, πB z)) ∘ qU =
        (fun p : HA × HB => (qA p.1, qB p.2)) ∘
          (fun x : HU => (interpretA x, interpretB x))) := by
  refine ⟨unification_as_common_refinement_paper qU interpretA qA
      interpretB qB πA routeUA routeA πB routeUB routeB liftA statusA liftB
      statusB statusU statusMapA statusMapB residualPassesStatus parentFormed
      rolePreserved, ?_⟩
  intro h
  exact common_refinement_square_of_exact_unifier qU interpretA qA
    interpretB qB πA πB parentFormed
    (LawStatusCarriage liftA statusA statusU statusMapA)
    (LawStatusCarriage liftB statusB statusU statusMapB)
    (TransportPreserved πA routeUA routeA)
    (TransportPreserved πB routeUB routeB)
    (RolePreservation rolePreserved)
    (CrossResidualClosed residualPassesStatus) h

/-- The exact projection equations force each parent kernel to contain the
kernel of the unifier quotient. -/
theorem exact_unifier_kernel_inclusion
    {HU QU HA QA HB QB : Type}
    (qU : HU → QU) (interpretA : HU → HA) (qA : HA → QA)
    (interpretB : HU → HB) (qB : HB → QB)
    (πA : QU → QA) (πB : QU → QB)
    (hA : πA ∘ qU = qA ∘ interpretA)
    (hB : πB ∘ qU = qB ∘ interpretB) :
    ∀ x x', qU x = qU x' →
      qA (interpretA x) = qA (interpretA x') ∧
        qB (interpretB x) = qB (interpretB x') := by
  intro x x' hxx'
  constructor
  · calc
      qA (interpretA x) = πA (qU x) := (congrFun hA x).symm
      _ = πA (qU x') := congrArg πA hxx'
      _ = qA (interpretA x') := congrFun hA x'
  · calc
      qB (interpretB x) = πB (qU x) := (congrFun hB x).symm
      _ = πB (qU x') := congrArg πB hxx'
      _ = qB (interpretB x') := congrFun hB x'

/-- F51 with the common-refinement square and both kernel inclusions. -/
theorem unification_as_common_refinement_paper_with_kernel
    {HU QU HA QA HB QB ClaimA ClaimB ClaimU StatusA StatusB StatusU
      CrossResidual : Type}
    (qU : HU → QU) (interpretA : HU → HA) (qA : HA → QA)
    (interpretB : HU → HB) (qB : HB → QB)
    (πA : QU → QA) (routeUA : QU → QU) (routeA : QA → QA)
    (πB : QU → QB) (routeUB : QU → QU) (routeB : QB → QB)
    (liftA : ClaimA → ClaimU) (statusA : ClaimA → StatusA)
    (liftB : ClaimB → ClaimU) (statusB : ClaimB → StatusB)
    (statusU : ClaimU → StatusU) (statusMapA : StatusA → StatusU)
    (statusMapB : StatusB → StatusU)
    (residualPassesStatus : CrossResidual → Prop)
    (parentFormed rolePreserved : Prop) :
    (ExactUnifier parentFormed
        (ObjectProjectionWithMap qU interpretA qA πA)
        (ObjectProjectionWithMap qU interpretB qB πB)
        (LawStatusCarriage liftA statusA statusU statusMapA)
        (LawStatusCarriage liftB statusB statusU statusMapB)
        (TransportPreserved πA routeUA routeA)
        (TransportPreserved πB routeUB routeB)
        (RolePreservation rolePreserved)
        (CrossResidualClosed residualPassesStatus) ↔
      parentFormed ∧
        πA ∘ qU = qA ∘ interpretA ∧
        πB ∘ qU = qB ∘ interpretB ∧
        (∀ u, πA (routeUA u) = routeA (πA u)) ∧
        (∀ u, πB (routeUB u) = routeB (πB u)) ∧
        (∀ k, statusU (liftA k) = statusMapA (statusA k)) ∧
        (∀ k, statusU (liftB k) = statusMapB (statusB k)) ∧
        rolePreserved ∧ (∀ residual, residualPassesStatus residual)) ∧
    (ExactUnifier parentFormed
        (ObjectProjectionWithMap qU interpretA qA πA)
        (ObjectProjectionWithMap qU interpretB qB πB)
        (LawStatusCarriage liftA statusA statusU statusMapA)
        (LawStatusCarriage liftB statusB statusU statusMapB)
        (TransportPreserved πA routeUA routeA)
        (TransportPreserved πB routeUB routeB)
        (RolePreservation rolePreserved)
        (CrossResidualClosed residualPassesStatus) →
      ((fun z : QU => (πA z, πB z)) ∘ qU =
        (fun p : HA × HB => (qA p.1, qB p.2)) ∘
          (fun x : HU => (interpretA x, interpretB x))) ∧
      ∀ x x', qU x = qU x' →
        qA (interpretA x) = qA (interpretA x') ∧
          qB (interpretB x) = qB (interpretB x')) := by
  have hprev := unification_as_common_refinement_paper_with_square qU
    interpretA qA interpretB qB πA routeUA routeA πB routeUB routeB
    liftA statusA liftB statusB statusU statusMapA statusMapB
    residualPassesStatus parentFormed rolePreserved
  refine ⟨hprev.1, ?_⟩
  intro h
  exact ⟨hprev.2 h, exact_unifier_kernel_inclusion qU interpretA qA
    interpretB qB πA πB h.2.1 h.2.2.1⟩

/-- The two projection equations alone give the square and kernel inclusion. -/
theorem common_refinement_square_and_kernel_of_projection_equations
    {HU QU HA QA HB QB : Type}
    (qU : HU → QU) (interpretA : HU → HA) (qA : HA → QA)
    (interpretB : HU → HB) (qB : HB → QB)
    (πA : QU → QA) (πB : QU → QB)
    (hA : πA ∘ qU = qA ∘ interpretA)
    (hB : πB ∘ qU = qB ∘ interpretB) :
    ((fun z : QU => (πA z, πB z)) ∘ qU =
      (fun p : HA × HB => (qA p.1, qB p.2)) ∘
        (fun x : HU => (interpretA x, interpretB x))) ∧
      (∀ x x', qU x = qU x' →
        qA (interpretA x) = qA (interpretA x') ∧
          qB (interpretB x) = qB (interpretB x')) := by
  constructor
  · funext x
    exact Prod.ext (congrFun hA x) (congrFun hB x)
  · exact exact_unifier_kernel_inclusion qU interpretA qA interpretB qB
      πA πB hA hB

/-- A surjective unifier quotient has exactly the joint projection kernel
precisely when its pairing of projections is injective. -/
theorem common_refinement_pair_injective_iff_kernel_exact
    {HU QU HA QA HB QB : Type}
    (qU : HU → QU) (interpretA : HU → HA) (qA : HA → QA)
    (interpretB : HU → HB) (qB : HB → QB)
    (πA : QU → QA) (πB : QU → QB)
    (hA : πA ∘ qU = qA ∘ interpretA)
    (hB : πB ∘ qU = qB ∘ interpretB)
    (hqU : Function.Surjective qU) :
    Function.Injective (fun z : QU => (πA z, πB z)) ↔
      ∀ x x' : HU, qU x = qU x' ↔
        qA (interpretA x) = qA (interpretA x') ∧
          qB (interpretB x) = qB (interpretB x') := by
  constructor
  · intro hinj x x'
    constructor
    · intro hxx
      exact (common_refinement_square_and_kernel_of_projection_equations
        qU interpretA qA interpretB qB πA πB hA hB).2 x x' hxx
    · rintro ⟨ha, hb⟩
      apply hinj
      exact Prod.ext ((congrFun hA x).trans (ha.trans (congrFun hA x').symm))
        ((congrFun hB x).trans (hb.trans (congrFun hB x').symm))
  · intro hkernel z z' hpair
    obtain ⟨x, rfl⟩ := hqU z
    obtain ⟨x', rfl⟩ := hqU z'
    apply (hkernel x x').2
    exact ⟨(congrFun hA x).symm.trans
        ((congrArg Prod.fst hpair).trans (congrFun hA x')),
      (congrFun hB x).symm.trans
        ((congrArg Prod.snd hpair).trans (congrFun hB x'))⟩

theorem unification_as_common_refinement_paper_exact_kernel
    {HU QU HA QA HB QB ClaimA ClaimB ClaimU StatusA StatusB StatusU
      CrossResidual : Type}
    (qU : HU → QU) (interpretA : HU → HA) (qA : HA → QA)
    (interpretB : HU → HB) (qB : HB → QB)
    (πA : QU → QA) (routeUA : QU → QU) (routeA : QA → QA)
    (πB : QU → QB) (routeUB : QU → QU) (routeB : QB → QB)
    (liftA : ClaimA → ClaimU) (statusA : ClaimA → StatusA)
    (liftB : ClaimB → ClaimU) (statusB : ClaimB → StatusB)
    (statusU : ClaimU → StatusU) (statusMapA : StatusA → StatusU)
    (statusMapB : StatusB → StatusU)
    (residualPassesStatus : CrossResidual → Prop)
    (parentFormed rolePreserved : Prop) :
(    (ExactUnifier parentFormed
        (ObjectProjectionWithMap qU interpretA qA πA)
        (ObjectProjectionWithMap qU interpretB qB πB)
        (LawStatusCarriage liftA statusA statusU statusMapA)
        (LawStatusCarriage liftB statusB statusU statusMapB)
        (TransportPreserved πA routeUA routeA)
        (TransportPreserved πB routeUB routeB)
        (RolePreservation rolePreserved)
        (CrossResidualClosed residualPassesStatus) ↔
      parentFormed ∧
        πA ∘ qU = qA ∘ interpretA ∧
        πB ∘ qU = qB ∘ interpretB ∧
        (∀ u, πA (routeUA u) = routeA (πA u)) ∧
        (∀ u, πB (routeUB u) = routeB (πB u)) ∧
        (∀ k, statusU (liftA k) = statusMapA (statusA k)) ∧
        (∀ k, statusU (liftB k) = statusMapB (statusB k)) ∧
        rolePreserved ∧ (∀ residual, residualPassesStatus residual)) ∧
    (ExactUnifier parentFormed
        (ObjectProjectionWithMap qU interpretA qA πA)
        (ObjectProjectionWithMap qU interpretB qB πB)
        (LawStatusCarriage liftA statusA statusU statusMapA)
        (LawStatusCarriage liftB statusB statusU statusMapB)
        (TransportPreserved πA routeUA routeA)
        (TransportPreserved πB routeUB routeB)
        (RolePreservation rolePreserved)
        (CrossResidualClosed residualPassesStatus) →
      ((fun z : QU => (πA z, πB z)) ∘ qU =
        (fun p : HA × HB => (qA p.1, qB p.2)) ∘
          (fun x : HU => (interpretA x, interpretB x))) ∧
      ∀ x x', qU x = qU x' →
        qA (interpretA x) = qA (interpretA x') ∧
          qB (interpretB x) = qB (interpretB x'))) ∧
    (∀ (_hA : πA ∘ qU = qA ∘ interpretA)
      (_hB : πB ∘ qU = qB ∘ interpretB),
      (((fun z : QU => (πA z, πB z)) ∘ qU =
          (fun p : HA × HB => (qA p.1, qB p.2)) ∘
            (fun x : HU => (interpretA x, interpretB x))) ∧
        (∀ x x', qU x = qU x' →
          qA (interpretA x) = qA (interpretA x') ∧
            qB (interpretB x) = qB (interpretB x'))) ∧
      (Function.Surjective qU →
        (Function.Injective (fun z : QU => (πA z, πB z)) ↔
          ∀ x x' : HU, qU x = qU x' ↔
            qA (interpretA x) = qA (interpretA x') ∧
              qB (interpretB x) = qB (interpretB x')))) := by
  refine ⟨unification_as_common_refinement_paper_with_kernel qU
    interpretA qA interpretB qB πA routeUA routeA πB routeUB routeB
    liftA statusA liftB statusB statusU statusMapA statusMapB
    residualPassesStatus parentFormed rolePreserved, ?_⟩
  intro hA hB
  exact ⟨common_refinement_square_and_kernel_of_projection_equations qU
    interpretA qA interpretB qB πA πB hA hB,
    fun hqU => common_refinement_pair_injective_iff_kernel_exact qU
      interpretA qA interpretB qB πA πB hA hB hqU⟩

end SixBirdsMetaMath.FoundationsIV.SelfReferenceLimits.Unification
