import SixBirdsMetaMath

#print axioms SixBirdsMetaMath.MetaMath.Foreclosure.TypeFiniteForeclosure.classify
#print axioms SixBirdsMetaMath.MetaMath.Foreclosure.TypeFiniteForeclosure.classify_spec
#print axioms SixBirdsMetaMath.RHNavier.ComplexGaussianNavierRHBridge.navierHeatWindowExcess_eq_rh_xi
#print axioms SixBirdsMetaMath.RHNavier.ComplexGaussianNavierRHBridge.actual_zero_gaussian_eq_navier_heat_readout
#print axioms SixBirdsMetaMath.RHNavier.ComplexGaussianNavierRHBridge.normalizedNonlinearFrameReadout
#print axioms SixBirdsMetaMath.RHNavierPvNP.ExternalSATGaussianLanguage.exists_positive_common_theta_time
#print axioms SixBirdsMetaMath.RHNavierPvNP.ExternalSATGaussianLanguage.gaussianSATLanguage_eq_L_SAT
#print axioms SixBirdsMetaMath.RHNavierPvNP.ProbePreservingTransportNoGo.no_probe_preserving_transport_to_sat
#print axioms SixBirdsMetaMath.RHNavier.JointSixBirdsObservationReturn.arithmetic_zero_window_closure_iff_rh
#print axioms SixBirdsMetaMath.RHNavier.JointSixBirdsObservationReturn.navier_global_mild_of_two_channel_closure
#print axioms SixBirdsMetaMath.RHNavier.JointSixBirdsObservationReturn.navier_pointwise_physical_pde_of_hilbert_xi_closure
#print axioms SixBirdsMetaMath.MetaMath.Foreclosure.CarrierDichotomy.sound_base_noncollapse
#print axioms SixBirdsMetaMath.MetaMath.Foreclosure.CarrierDichotomy.nonXEquivalent_and_xEquivalent
