/-!
F2 Descent-Repair Normal Form.

The source law says that an upstairs transport descends through a source
quotient and target quotient exactly when it has no split-pair obstruction:
two source-indistinguishable upstairs points may not be separated after
transport and target quotienting.
-/

namespace SixBirdsMetaMath.FoundationsIV.Transport.DescentRepair

/-- The split-pair obstruction for a source quotient `q`, upstairs transport
`F`, and target quotient `r`. -/
def splitPairObstruction {X Q Y R : Type} (q : X → Q) (F : X → Y)
    (r : Y → R) : (X × X) → Prop :=
  fun pair => q pair.1 = q pair.2 ∧ r (F pair.1) ≠ r (F pair.2)

/-- Predicate-level emptiness for an obstruction family. -/
def ObstructionEmpty {A : Type} (obstruction : A → Prop) : Prop :=
  ∀ a, ¬ obstruction a

/-- The paper's descent predicate: a lower transport `Q -> R` fills the square
`Fbar ∘ q = r ∘ F`. -/
def Descends {X Q Y R : Type} (q : X → Q) (F : X → Y) (r : Y → R) : Prop :=
  ∃ Fbar : Q → R, Fbar ∘ q = r ∘ F

/-- A source refinement is finer than the original source quotient: equality in
the refined source quotient implies equality in the original source quotient. -/
def SourceRefinement {X Q Q' : Type} (q' : X → Q') (q : X → Q) : Prop :=
  ∀ ⦃x x' : X⦄, q' x = q' x' → q x = q x'

/-- A target coarsening is coarser than the original target quotient: target
equality for `r` remains equality after replacing `r` by `r'`. -/
def TargetCoarsening {Y R R' : Type} (r : Y → R) (r' : Y → R') : Prop :=
  ∀ ⦃y y' : Y⦄, r y = r y' → r' y = r' y'

/-- The target equivalence generated by identifying `r (F x)` and
`r (F x')` whenever the source quotient identifies `x` and `x'`. This is the
paper's least target-side repair relation. -/
inductive TargetRepairRel {X Q Y R : Type} (q : X → Q) (F : X → Y)
    (r : Y → R) : R → R → Prop where
  | refl (a : R) : TargetRepairRel q F r a a
  | symm {a b : R} :
      TargetRepairRel q F r a b → TargetRepairRel q F r b a
  | trans {a b c : R} :
      TargetRepairRel q F r a b →
      TargetRepairRel q F r b c →
      TargetRepairRel q F r a c
  | gen (x x' : X) :
      q x = q x' → TargetRepairRel q F r (r (F x)) (r (F x'))

/-- The canonical target repair quotient: the original target carrier modulo
the generated repair relation. -/
def TargetRepairQuotient {X Q Y R : Type} (q : X → Q) (F : X → Y)
    (r : Y → R) : Type :=
  Quot (TargetRepairRel q F r)

/-- The quotient map from the original target carrier into the canonical target
repair quotient. -/
def targetRepairQuotient {X Q Y R : Type} (q : X → Q) (F : X → Y)
    (r : Y → R) : R → TargetRepairQuotient q F r :=
  Quot.mk (TargetRepairRel q F r)

/-- The repaired target quotient map on `Y`, obtained by composing the old
target quotient with the canonical target repair quotient. -/
def targetRepairMap {X Q Y R : Type} (q : X → Q) (F : X → Y)
    (r : Y → R) : Y → TargetRepairQuotient q F r :=
  targetRepairQuotient q F r ∘ r

/-- The terminal target coarsening remains available as a fallback, but it is
not the canonical/minimal target repair. -/
def terminalTargetCoarsening {Y : Type} : Y → Unit :=
  fun _ => ()

/-- The canonical source-side repair records both the old source class and the
transported target class. -/
def sourceRepairQuotient {X Q Y R : Type} (q : X → Q) (F : X → Y)
    (r : Y → R) : X → Q × R :=
  fun x => (q x, r (F x))

/-- The source-side repair is indeed a refinement of the original source
quotient. -/
theorem source_repair_refines {X Q Y R : Type} (q : X → Q) (F : X → Y)
    (r : Y → R) :
    SourceRefinement (sourceRepairQuotient q F r) q := by
  intro x x' h
  exact congrArg Prod.fst h

/-- After source repair, the upstairs transport descends by projecting the
stored target class. -/
theorem source_repair_descends {X Q Y R : Type} (q : X → Q) (F : X → Y)
    (r : Y → R) :
    Descends (sourceRepairQuotient q F r) F r := by
  refine ⟨Prod.snd, ?_⟩
  funext x
  rfl

/-- The source-side repair closes the split-pair obstruction. -/
theorem source_repair_closes_obstruction {X Q Y R : Type} (q : X → Q)
    (F : X → Y) (r : Y → R) :
    ObstructionEmpty (splitPairObstruction (sourceRepairQuotient q F r) F r) := by
  intro pair h
  rcases pair with ⟨x, x'⟩
  exact h.2 (congrArg Prod.snd h.1)

/-- The generated target repair is a coarsening of the original target
quotient. -/
theorem target_repair_coarsens {X Q Y R : Type} (q : X → Q) (F : X → Y)
    (r : Y → R) :
    TargetCoarsening r (targetRepairMap q F r) := by
  intro y y' h
  exact congrArg (targetRepairQuotient q F r) h

/-- After canonical target repair, the upstairs transport descends through the
declared source quotient. The surjectivity hypothesis records that `q` is a
quotient map onto its carrier. -/
theorem target_repair_descends {X Q Y R : Type} (q : X → Q) (F : X → Y)
    (r : Y → R) (hq : Function.Surjective q) :
    Descends q F (targetRepairMap q F r) := by
  classical
  let Fbar : Q → TargetRepairQuotient q F r :=
    fun z => targetRepairQuotient q F r (r (F (Classical.choose (hq z))))
  refine ⟨Fbar, ?_⟩
  funext x
  unfold Fbar targetRepairMap Function.comp
  let x0 : X := Classical.choose (hq (q x))
  have hx0 : q x0 = q x := Classical.choose_spec (hq (q x))
  change targetRepairQuotient q F r (r (F x0)) =
    targetRepairQuotient q F r (r (F x))
  exact Quot.sound (TargetRepairRel.gen x0 x hx0)

/-- The canonical generated target-side repair closes the split-pair
obstruction. -/
theorem target_repair_closes_obstruction {X Q Y R : Type} (q : X → Q)
    (F : X → Y) (r : Y → R) :
    ObstructionEmpty (splitPairObstruction q F (targetRepairMap q F r)) := by
  intro pair h
  rcases pair with ⟨x, x'⟩
  rcases h with ⟨hsource, htarget_ne⟩
  exact htarget_ne (Quot.sound (TargetRepairRel.gen x x' hsource))

/-- Universal property of the canonical target repair: any target coarsening
`c : R -> C` that makes `c ∘ r ∘ F` descend through `q` factors through the
generated repair quotient. -/
theorem target_repair_universal {X Q Y R C : Type} (q : X → Q) (F : X → Y)
    (r : Y → R) (c : R → C) (hdesc : Descends q F (c ∘ r)) :
    ∃ cbar : TargetRepairQuotient q F r → C,
      cbar ∘ targetRepairQuotient q F r = c := by
  rcases hdesc with ⟨Fbar, hcomm⟩
  have hrespect :
      ∀ ⦃a b : R⦄, TargetRepairRel q F r a b → c a = c b := by
    intro a b hrel
    induction hrel with
    | refl a => rfl
    | symm hrel ih => exact ih.symm
    | trans hleft hright ihleft ihright => exact ihleft.trans ihright
    | gen x x' hsource =>
        have hx : Fbar (q x) = c (r (F x)) := congrFun hcomm x
        have hx' : Fbar (q x') = c (r (F x')) := congrFun hcomm x'
        calc
          c (r (F x)) = Fbar (q x) := hx.symm
          _ = Fbar (q x') := by rw [hsource]
          _ = c (r (F x')) := hx'
  let cbar : TargetRepairQuotient q F r → C :=
    Quot.lift c (fun a b hrel => hrespect hrel)
  refine ⟨cbar, ?_⟩
  funext a
  rfl

/-- The terminal fallback coarsening is a coarsening of every target quotient. -/
theorem terminal_target_coarsening_coarsens {Y R : Type} (r : Y → R) :
    TargetCoarsening r (terminalTargetCoarsening : Y → Unit) := by
  intro y y' h
  rfl

/-- The terminal fallback descends, so by the universal property it factors
through the canonical generated target repair. -/
theorem terminal_target_coarsening_factors_through_repair {X Q Y R : Type}
    (q : X → Q) (F : X → Y) (r : Y → R) :
    ∃ cbar : TargetRepairQuotient q F r → Unit,
      cbar ∘ targetRepairQuotient q F r = (fun _ : R => ()) := by
  exact target_repair_universal q F r (fun _ : R => ())
    ⟨fun _ => (), by funext x; rfl⟩

/--
Descent-Repair Normal Form: for a source quotient map `q`, an upstairs
transport descends through `(q, r)` if and only if the split-pair obstruction
is empty.

The explicit `Function.Surjective q` hypothesis is the Lean expression of
`q : X -> Q` being a quotient map onto its declared quotient carrier.
-/
theorem descent_repair_normal_form {X Q Y R : Type} (q : X → Q) (F : X → Y)
    (r : Y → R) (hq : Function.Surjective q) :
    Descends q F r ↔ ObstructionEmpty (splitPairObstruction q F r) := by
  constructor
  · intro hdesc
    rcases hdesc with ⟨Fbar, hcomm⟩
    intro pair hpair
    rcases pair with ⟨x, x'⟩
    rcases hpair with ⟨hsource, htarget_ne⟩
    have hx : Fbar (q x) = r (F x) := congrFun hcomm x
    have hx' : Fbar (q x') = r (F x') := congrFun hcomm x'
    have htarget : r (F x) = r (F x') := by
      calc
        r (F x) = Fbar (q x) := hx.symm
        _ = Fbar (q x') := by rw [hsource]
        _ = r (F x') := hx'
    exact htarget_ne htarget
  · intro hempty
    classical
    let Fbar : Q → R := fun z => r (F (Classical.choose (hq z)))
    refine ⟨Fbar, ?_⟩
    funext x
    unfold Fbar
    let x0 : X := Classical.choose (hq (q x))
    have hx0 : q x0 = q x := Classical.choose_spec (hq (q x))
    change r (F x0) = r (F x)
    exact Classical.byContradiction (fun hneq =>
      False.elim (hempty (x0, x) ⟨hx0, hneq⟩))

/-- Closed-obstruction formulation of the target repair universal property:
among target coarsenings that close the split-pair obstruction, the generated
repair quotient is the finest one. -/
theorem target_repair_universal_of_closes_obstruction {X Q Y R C : Type}
    (q : X → Q) (F : X → Y) (r : Y → R) (c : R → C)
    (hq : Function.Surjective q)
    (hempty : ObstructionEmpty (splitPairObstruction q F (c ∘ r))) :
    ∃ cbar : TargetRepairQuotient q F r → C,
      cbar ∘ targetRepairQuotient q F r = c := by
  exact target_repair_universal q F r c
    ((descent_repair_normal_form q F (c ∘ r) hq).2 hempty)

/-- Every source refinement through which the transport descends also refines
the canonical source repair. Thus the repair has the largest kernel among such
refinements. -/
theorem source_repair_coarsest {X Q Q' Y R : Type} (q : X → Q)
    (F : X → Y) (r : Y → R) (q' : X → Q')
    (href : SourceRefinement q' q) (hdesc : Descends q' F r) :
    ∀ x x', q' x = q' x' →
      sourceRepairQuotient q F r x = sourceRepairQuotient q F r x' := by
  rcases hdesc with ⟨Fbar, hcomm⟩
  intro x x' hsource
  have htarget : r (F x) = r (F x') := by
    calc
      r (F x) = Fbar (q' x) := (congrFun hcomm x).symm
      _ = Fbar (q' x') := congrArg Fbar hsource
      _ = r (F x') := congrFun hcomm x'
  exact Prod.ext (href hsource) htarget

/-- A map out of the target repair quotient makes the coarsened transport
descend through the original source quotient. -/
theorem target_repair_universal_converse {X Q Y R C : Type} (q : X → Q)
    (F : X → Y) (r : Y → R) (c : R → C)
    (hq : Function.Surjective q)
    (hfactor : ∃ d : TargetRepairQuotient q F r → C,
      d ∘ targetRepairQuotient q F r = c) :
    Descends q F (c ∘ r) := by
  rcases hfactor with ⟨d, hd⟩
  rcases target_repair_descends q F r hq with ⟨Fbar, hcomm⟩
  refine ⟨d ∘ Fbar, ?_⟩
  funext x
  have hx : Fbar (q x) = targetRepairQuotient q F r (r (F x)) :=
    congrFun hcomm x
  have hr : d (targetRepairQuotient q F r (r (F x))) = c (r (F x)) :=
    congrFun hd (r (F x))
  change d (Fbar (q x)) = c (r (F x))
  rw [hx]
  exact hr

/-- Descent after target coarsening is equivalent to factorization through the
canonical target repair quotient. -/
theorem target_repair_universal_iff {X Q Y R C : Type} (q : X → Q)
    (F : X → Y) (r : Y → R) (c : R → C)
    (hq : Function.Surjective q) :
    Descends q F (c ∘ r) ↔
      ∃ d : TargetRepairQuotient q F r → C,
        d ∘ targetRepairQuotient q F r = c := by
  constructor
  · exact target_repair_universal q F r c
  · exact target_repair_universal_converse q F r c hq

/-- The strengthened paper statement of Descent--Repair Normal Form: the
split-pair criterion, the coarsest source refinement, and the target repair
factorization criterion. -/
theorem paper_descent_repair_normal_form {X Q Y R : Type} (q : X → Q)
    (F : X → Y) (r : Y → R) (hq : Function.Surjective q) :
    (Descends q F r ↔ ObstructionEmpty (splitPairObstruction q F r)) ∧
    (SourceRefinement (sourceRepairQuotient q F r) q ∧
      Descends (sourceRepairQuotient q F r) F r ∧
      ∀ {Q' : Type} (q' : X → Q'),
        SourceRefinement q' q → Descends q' F r →
          ∀ x x', q' x = q' x' →
            sourceRepairQuotient q F r x = sourceRepairQuotient q F r x') ∧
    (∀ {C : Type} (c : R → C),
      Descends q F (c ∘ r) ↔
        ∃ d : TargetRepairQuotient q F r → C,
          d ∘ targetRepairQuotient q F r = c) := by
  refine ⟨descent_repair_normal_form q F r hq,
    ⟨source_repair_refines q F r, source_repair_descends q F r, ?_⟩, ?_⟩
  · intro Q' q' href hdesc
    exact source_repair_coarsest q F r q' href hdesc
  · intro C c
    exact target_repair_universal_iff q F r c hq

/-- A surjective refinement that admits descent carries a map to the canonical
source repair, making the source repair factor through that refinement. -/
theorem source_repair_factors_through_refinement {X Q Q' Y R : Type}
    (q : X → Q) (F : X → Y) (r : Y → R) (q' : X → Q')
    (hq' : Function.Surjective q') (href : SourceRefinement q' q)
    (hdesc : Descends q' F r) :
    ∃ g : Q' → Q × R, g ∘ q' = sourceRepairQuotient q F r := by
  classical
  let g : Q' → Q × R := fun z =>
    sourceRepairQuotient q F r (Classical.choose (hq' z))
  refine ⟨g, ?_⟩
  funext x
  change sourceRepairQuotient q F r (Classical.choose (hq' (q' x))) =
    sourceRepairQuotient q F r x
  exact source_repair_coarsest q F r q' href hdesc _ _
    (Classical.choose_spec (hq' (q' x)))

/-- The paper's descent-repair normal form with both the kernel and map forms
of the universal source repair property. -/
theorem paper_descent_repair_normal_form' {X Q Y R : Type} (q : X → Q)
    (F : X → Y) (r : Y → R) (hq : Function.Surjective q) :
    (Descends q F r ↔ ObstructionEmpty (splitPairObstruction q F r)) ∧
    (SourceRefinement (sourceRepairQuotient q F r) q ∧
      Descends (sourceRepairQuotient q F r) F r ∧
      (∀ {Q' : Type} (q' : X → Q'),
        SourceRefinement q' q → Descends q' F r →
          ∀ x x', q' x = q' x' →
            sourceRepairQuotient q F r x = sourceRepairQuotient q F r x') ∧
      (∀ {Q' : Type} (q' : X → Q'),
        Function.Surjective q' → SourceRefinement q' q → Descends q' F r →
          ∃ g : Q' → Q × R, g ∘ q' = sourceRepairQuotient q F r)) ∧
    (∀ {C : Type} (c : R → C),
      Descends q F (c ∘ r) ↔
        ∃ d : TargetRepairQuotient q F r → C,
          d ∘ targetRepairQuotient q F r = c) := by
  rcases paper_descent_repair_normal_form q F r hq with
    ⟨hcriterion, hsource, htarget⟩
  refine ⟨hcriterion, ⟨hsource.1, hsource.2.1, hsource.2.2, ?_⟩, htarget⟩
  intro Q' q' hq' href hdesc
  exact source_repair_factors_through_refinement q F r q' hq' href hdesc

/-- The canonical repair factors through any map carrying both component
readouts; the intermediate map need not be surjective. -/
theorem source_repair_factors_through_maps {X Q Q' Y R : Type}
    (q : X → Q) (F : X → Y) (r : Y → R)
    (q' : X → Q') (a : Q' → Q) (b : Q' → R)
    (hq : q = a ∘ q') (hr : r ∘ F = b ∘ q') :
    sourceRepairQuotient q F r = (fun z => (a z, b z)) ∘ q' := by
  funext x
  exact Prod.ext (congrFun hq x) (congrFun hr x)

/-- F2 with the map form of source minimality for every refinement, including
non-surjective presentations. -/
theorem paper_descent_repair_normal_form_maps {X Q Y R : Type}
    (q : X → Q) (F : X → Y) (r : Y → R)
    (hq : Function.Surjective q) :
    (Descends q F r ↔ ObstructionEmpty (splitPairObstruction q F r)) ∧
    (SourceRefinement (sourceRepairQuotient q F r) q ∧
      Descends (sourceRepairQuotient q F r) F r ∧
      (∀ {Q' : Type} (q' : X → Q'),
        SourceRefinement q' q → Descends q' F r →
          ∀ x x', q' x = q' x' →
            sourceRepairQuotient q F r x = sourceRepairQuotient q F r x') ∧
      (∀ {Q' : Type} (q' : X → Q') (a : Q' → Q) (b : Q' → R),
        q = a ∘ q' → r ∘ F = b ∘ q' →
          sourceRepairQuotient q F r = (fun z => (a z, b z)) ∘ q')) ∧
    (∀ {C : Type} (c : R → C),
      Descends q F (c ∘ r) ↔
        ∃ d : TargetRepairQuotient q F r → C,
          d ∘ targetRepairQuotient q F r = c) := by
  rcases paper_descent_repair_normal_form q F r hq with
    ⟨hcriterion, hsource, htarget⟩
  exact ⟨hcriterion, ⟨hsource.1, hsource.2.1, hsource.2.2,
    fun q' a b hqa hrb => source_repair_factors_through_maps q F r q' a b hqa hrb⟩,
    htarget⟩

end SixBirdsMetaMath.FoundationsIV.Transport.DescentRepair
