import ClosureLadder
import SixBirds
import SixBirdsIII

/-!
Imported Foundations surface for the needles Lean skeleton.
Generated by scripts/generate_imported_foundations.py from
formalization/inventory/imported_foundations.yml.
Do not edit by hand.

Build-failure here means a foundations Lean decl drifted upstream;
re-run the generator and audit the cross-walk yml.
-/

#check ClosureOp
#check ClosureLadder
#check ClosureLadder.IdempotentEndo
#check ClosureLadder.MetaPackaging.pack

#check SixBirds.Role
#check SixBirds.FATCD
#check SixBirds.ChannelStatus
#check SixBirds.scoped_exact_six
#check SixBirds.typed_non_collapse

#check SixBirdsIII.BirdIntDomain
#check SixBirdsIII.Primitive
#check SixBirdsIII.PromotionStatus
#check SixBirdsIII.ClaimStatus
#check SixBirdsIII.GateStatus
#check SixBirdsIII.PromotionBridgeRecord
#check SixBirdsIII.ClaimRecord
#check SixBirdsIII.DefectRecord
#check SixBirdsIII.Level
#check SixBirdsIII.Host
#check SixBirdsIII.DirectedCellRecord
#check SixBirdsIII.TopDownChannelRecord
#check SixBirdsIII.ThresholdTag
#check SixBirdsIII.VisibilityTag
#check SixBirdsIII.StrictGateStatus
#check SixBirdsIII.SqStatus
