#!/usr/bin/env python3
"""Generate lean/SixBirdsMetaMath/ImportedFoundations.lean from the cross-walk yml.

Reads formalization/inventory/imported_foundations.yml and emits one
`#check` per entry, grouped by foundation_id. The resulting file is the
drift canary: if a foundations Lean decl is renamed upstream, the
`#check` fails to type-check at `lake build` time.

Run with `--check` to validate that the committed
ImportedFoundations.lean matches what we would generate from the
current cross-walk yml.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Reuse the audit script's cross-walk parser to avoid duplicating logic.
sys.path.insert(0, str(Path(__file__).resolve().parent))
import audit_foundations_dependencies as audit  # noqa: E402


ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "lean" / "SixBirdsMetaMath" / "ImportedFoundations.lean"

# Foundation order in the emitted file and matching imports.
FOUNDATION_ORDER = ["foundations_i", "foundations_ii", "foundations_iii"]
FOUNDATION_IMPORT = {
    "foundations_i": "ClosureLadder",
    "foundations_ii": "SixBirds",
    "foundations_iii": "SixBirdsIII",
}


def render() -> str:
    entries = audit.parse_imported_foundations()
    grouped: dict[str, list[str]] = {fid: [] for fid in FOUNDATION_ORDER}
    for entry in entries:
        fid = entry.get("foundation_id", "")
        lean_decl = entry.get("lean_decl", "")
        if fid not in grouped or not lean_decl:
            continue
        if lean_decl not in grouped[fid]:
            grouped[fid].append(lean_decl)

    lines: list[str] = []
    for fid in FOUNDATION_ORDER:
        lines.append(f"import {FOUNDATION_IMPORT[fid]}")
    lines.append("")
    lines.append("/-!")
    lines.append("Imported Foundations surface for the needles Lean skeleton.")
    lines.append("Generated by scripts/generate_imported_foundations.py from")
    lines.append("formalization/inventory/imported_foundations.yml.")
    lines.append("Do not edit by hand.")
    lines.append("")
    lines.append("Build-failure here means a foundations Lean decl drifted upstream;")
    lines.append("re-run the generator and audit the cross-walk yml.")
    lines.append("-/")
    lines.append("")
    for fid in FOUNDATION_ORDER:
        if not grouped[fid]:
            continue
        for decl in grouped[fid]:
            lines.append(f"#check {decl}")
        lines.append("")
    return "\n".join(lines)


def write() -> int:
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    rendered = render()
    TARGET.write_text(rendered, encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)} ({rendered.count(chr(10)) + 1} lines)")
    return 0


def check() -> int:
    if not TARGET.exists():
        print(f"ERROR: missing {TARGET.relative_to(ROOT)}; rerun generator", file=sys.stderr)
        return 1
    expected = render()
    if TARGET.read_text(encoding="utf-8") != expected:
        print(
            f"ERROR: {TARGET.relative_to(ROOT)} is stale; rerun "
            "scripts/generate_imported_foundations.py",
            file=sys.stderr,
        )
        return 1
    print("imported foundations surface is current")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="validate ImportedFoundations.lean matches the cross-walk yml",
    )
    args = parser.parse_args()
    if args.check:
        return check()
    return write()


if __name__ == "__main__":
    raise SystemExit(main())
